### ISSUE TITLE
Compile Error when enabling #define SolidBedMounts option in DW6

### ISSUE THREAD

**Issue by StreckerCM** [InsanityAutomation/Marlin#111]
### Description

Compiling sketch with #define SolidBedMounts enabled it fails for Arduino Mega or Mega 2560.  I wanted to use this option on my CR10S Pro with solid bed mounts.

### Steps to Reproduce

1. Open Marlin.ino
2. Uncomment #define SolidBedMounts
3. Verify Sketch

**Expected behavior:** [What you expect to happen]

Sketch compiles without errors

**Actual behavior:** [What actually happens]

Error Compiling for board Arduino Mega or Mega 2560

#### Additional Information

* [Error_Output.zip](https://github.com/InsanityAutomation/Marlin/files/4395393/Error_Output.zip) - Verbose compiler output
* [Configuration.zip](https://github.com/InsanityAutomation/Marlin/files/4395390/Configuration.zip) - containing `Configuration.h` and `Configuration_adv.h` files.

**Comment by InsanityAutomation** [comment]
Solid bed mounts doesnt do anything for the touchscreen. All it does is remove a menu from the graphical lcd for level corners, but the touchscreen needs the points behind it. Ill add a check to undefine it for touchscreens.
