### ISSUE TITLE
Which parameters do I have to set for my CR-X (CRX_BLT_UBL_Fil)

### ISSUE THREAD

**Issue by LMS0815** [InsanityAutomation/Marlin#113]
All,

I do not have any success compiling a FW for my Creality CR-X (and I cyn not find any examples inf 
`Configurations-bugfix-2.0.x.zip`

This is what I am trying...
Active defines in configuration.h:
```
  #define MachineCRX
  #define HotendStock
  #define BedDC
  #define ABL_BLTOUCH
  #define GraphicLCD
  #define ForceCRXDisplay
  #define ABL_UBL
  #define DualFilSensors
  #define MeshFine

  #define LowMemoryBoard  //  no //#define BLTOUCH_HS_MODE


```
  Active defines in Configuration_adv.h

```
  - http://marlinfw.org/docs/gcode/M851.html
  - Same as UBL Z-Offset
  #define NOZZLE_TO_PROBE_OFFSET { -10.9, -41.6, -2.40 }


```  Compiling for board:
`  Arduino Mega or Mega 2560 / Atmega2560
`

**Comment by InsanityAutomation** [comment]
#define GraphicLCD
  #define ForceCRXDisplay

These conflict with each other, are you using a 12864 display or stock display?

**Comment by LMS0815** [comment]
My CR-X is having a stock display. 

![touch 1](https://user-images.githubusercontent.com/8235214/78498839-195e0280-774d-11ea-9dab-1da6aaab5f25.png)


Its workinf fine with: CRX_BLT_UBL_Fil_DW6.hex

**Comment by LMS0815** [comment]
THX I compiled using
```
//#define GraphicLCD
#define ForceCRXDisplay

```
*.hex file was created. But I get am _low memory_ warning. The file is much bigger than CRX_BLT_UBL_NoFil_DW6.hex.
