### ISSUE TITLE
Incompatibility of #Defines in both CONTROLLER_FAN and Configuration_adv.h

### ISSUE THREAD

**Issue by mark2382** [InsanityAutomation/Marlin#114]
### Description

Compiling for SKR PRO 1.1 o n CR10S-PRO. Stock pull from git for CrealityDwin_2.0. 

Using Visual Studio Code with platform.io plugin.

In Configuration_adv.h:
Error: CONTROLERFAN_SPEED needs to be changed to CONTROLLERFAN_SPEED_ACTIVE, There also needs to be a CONTROLLERFAN_SPEED_MIN #define as in latest Marlin. 

[config_and_platform.io.zip](https://github.com/InsanityAutomation/Marlin/files/4412912/config_and_platform.io.zip)

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by InsanityAutomation** [comment]
A full sync of the config and head code is done periodically. This will get updated in the next round.
