### ISSUE TITLE
TM Info Screens after update issue

### ISSUE THREAD

**Issue by masc2279** [InsanityAutomation/Marlin#115]
### Description

images and data on progress screen do not align and is missing items based on the background image. Looks like it still thinks the stock screens are there vs the CR-XABL_Screens_V2Rev1.7z screens as seen on image below

![TouchScreen](https://user-images.githubusercontent.com/1273722/78404061-df5cf700-75ba-11ea-925f-bdfc22831984.jpeg)

### Steps to Reproduce

1. Get CrealityDwin_2.0
2. Configure for CR10XMax
3. Upload firmware to printer
4. Upload CR-XABL_Screens_V2Rev1.7z to screen.
5. Start Print

**Expected behavior:** Data should be present and aligned on screen

**Actual behavior:** Missing data and alignment is based on stock screens

**Comment by InsanityAutomation** [comment]
It sounds like something went wrong packaging the CRX screens. Ill go over them this weekend.

**Comment by masc2279** [comment]
Thank you !

**Comment by InsanityAutomation** [comment]
Fixed, the uploaded archive had 2 bin files inside, the naming the dgus tool uses and what the screen looks for. Correct data was in the default export name and the screen used the old files! Regardless, fresh archive is loaded. If anything was missed, just reopen the issue.

**Comment by masc2279** [comment]
Screens  look good opened another ticket up for CrealityDwin2.0_Bleeding   the sounds are all not working or broken uploaded audio recording as well on that ticket.  

Thanks for your help.

**Comment by LMS0815** [comment]
I am facing the same issue. 
Where can I find `CR-XABL_Screens_V2Rev1.x.7z` version?
Version `CR-XABL_Screens_V2Rev1.1.7z ` looks strange to me.

`/DWIN_SET/` contains 4 `*.bin` files and a sub folder `/14/` containing a file `bin.` as well. I assume it should be `14.bin` and not `14/bin.`.


Found: https://github.com/InsanityAutomation/Marlin/blob/CrealityDwin2.0_Bleeding/CR-XABL_Screens_V2Rev2.7z

**Comment by masc2279** [comment]
> I am facing the same issue.
> Where can I find `CR-XABL_Screens_V2Rev1.x.7z` version?
> Version `CR-XABL_Screens_V2Rev1.1.7z ` looks strange to me.
> 
> `/DWIN_SET/` contains 4 `*.bin` files and a sub folder `/14/` containing a file `bin.` as well. I assume it should be `14.bin` and not `14/bin.`.
> 
> Found: https://github.com/InsanityAutomation/Marlin/blob/CrealityDwin2.0_Bleeding/CR-XABL_Screens_V2Rev2.7z

Just a heads up that the screens work in that file but there is a sound bug that i have opened on that you might want to set your sound down to mute .... But the screens do work at least on my machine now

**Comment by LMS0815** [comment]
Thank you. 
@masc2279 I can not reproduce the sound bug with my CR-X (**CRX_BLT_UBL_Fil_DW6.hex**). I just needed to lower volume, which is 100% after update.
