### ISSUE TITLE
Sounds are broken CR-10MAX - CrealityDwin2.0_Bleeding

### ISSUE THREAD

**Issue by masc2279** [InsanityAutomation/Marlin#116]
[Printer Sounds.m4a.zip](https://github.com/InsanityAutomation/Marlin/files/4434575/Printer.Sounds.m4a.zip)

Steps to Reproduce

1. Get CrealityDwin2.0_Bleeding
2. Configure for CR10XMax
3. Upload firmware to printer
4. Upload CR-XABL_Screens_V2Rev2.7z to screen.

Boot printer

Expected behavior: Touch screen sounds should be normal and clear.

Actual behavior: Touch screen sounds and boot up sounds are broken and damaged. Large squeaks and scrapes sounds are heard.

**Comment by rc-fire** [comment]
I just tried to install the tiny machines firmware on a fairly new CR10S Pro V2 and got the exact same issue after the LCD firmware update. Did you find a way to fix it or is there more information on this? (I am also unable to start auto bed leveling from the LCD while over gcode everything works fine - I just mention it here in case it might be related)

**Comment by masc2279** [comment]
No sounds have not been fixed nor has someone started looking into it ....  As for leveling on the 10MAX it works like a charm.  I also went to non bleeding codebase using the new screens and it works minus the sounds so if your having issues just update the screens and use the normal 2.0 version branch for code

**Comment by masc2279** [comment]
> I just tried to install the tiny machines firmware on a fairly new CR10S Pro V2 and got the exact same issue after the LCD firmware update. Did you find a way to fix it or is there more information on this? (I am also unable to start auto bed leveling from the LCD while over gcode everything works fine - I just mention it here in case it might be related)

No sounds have not been fixed nor has someone started looking into it .... As for leveling on the 10MAX it works like a charm. I also went to non bleeding codebase using the new screens and it works minus the sounds so if your having issues just update the screens and use the normal 2.0 version branch for code

**Comment by barrarot** [comment]
Hi everyone, if it helps, I am also getting this issue of broken noises on my stock cr10s pro(May 2019) too, the following is what I did: 

1)installed http://insanityautomation.com/Firmware/Creality/SingleExtruderScreens_V2Rev1.1.7z dwin_set from tiny machines (https://tiny-machines-3d.myshopify.com/pages/10spro), which links to this repo, and installed it to the LCD. 

2)In addition installed http://insanityautomation.com/Firmware/Creality/10SPro_BIL_DW6.hex.gz from tiny machines, which also links to this repo. I just had to unzip the compression of .gz(to just a .hex), and installed through Cura and a usb connection.

**Comment by pat931** [comment]
Hi everyone, if it helps, I am also getting this issue of broken noises on my stock cr10s pro(May 2019) too, the following is what I did:

1)installed http://insanityautomation.com/Firmware/Creality/SingleExtruderScreens_V2Rev1.1.7z dwin_set from tiny machines (https://tiny-machines-3d.myshopify.com/pages/10spro), which links to this repo, and installed it to the LCD.

2)In addition installed http://insanityautomation.com/Firmware/Creality/10SPro_BIL_DW6.hex.gz from tiny machines, which also links to this repo. I just had to unzip the compression of .gz(to just a .hex), and installed through Cura and a usb connection.

**Comment by Myrddinwylit** [comment]
Like pat931 - I followed the Same directions as above. On my Stock Cr10s pro (v1 with Stock Probe)
The sound is not working properly. Turned off the Sound for Now (however they default back on when i restart my printer). I get the Same Sounds as Masc2279 above  -

**Comment by pat931** [comment]
On that note from myrddinwylit above - It also resets my sounds settings every time I restart the machine. Anyway that when this issue gets resolved that also it could save the set sound level to persist beyond restart. If not maybe a feature request?

**Comment by quarky42** [comment]
I've got no sound on my Ender 5 Plus.  I do have sound on my CR-10S Pro.

The first time I went to update the CR-10S Pro, I didn't know if I needed only the DWIN_SET folder or if I needed all the files from the Single Screen package so I just included all the files.

When I updated the Ender 5 Plus I just copied the DWIN_SET folder and nothing else.  

I'll see if I can get some time early next week to try copying all the files over on the Ender 5 Plus to see if that does the trick. 

Has anyone else tried this yet?

**Comment by Myrddinwylit** [comment]
Any Updates on this Issue.. I am not sure if the fix is as simple as what quarky42 did. Where is the single screen package?

**Comment by quarky42** [comment]
I haven't had a chance to take the bottom cover off and try some variations on updating the touch screen yet.  It is on my todo list, but I have had some other things keeping me busy.

**Comment by MaltWhiskey** [comment]
i had the same issue, getting the wav files form an older screen version fixed the issue. Just replace all the wav files and update the screen again and done.

**Comment by Myrddinwylit** [comment]
Can someone post the link to the older sound files - it’s not a major problem but would like to fix this

**Comment by masc2279** [comment]
Just pulled todays latest   CrealityDwin2.0_Bleeding   branch which includes latest     bugfix-2.0.x   Bug and new fixes and this issue still exists and has not been resolved ....

**Comment by clifjones** [comment]
I have a stock Cr10S Pro and had broken sound on DW6.  DW5 screen .WAV files didn't fix it but the B7 screen .WAV files did correct the issue.  Hopefully this helps others.

**Comment by pat931** [comment]
Hi everyone, Im still having issues with sound on my cr10s pro stock version. Has anyone had any new luck with the newest release DW7? @clifjones you mention B7 screen .wav files and @MaltWhiskey you mention old .wav files. Is there a place I can download these? Thanks.

**Comment by JarrettWendt** [comment]
I had this problem and it turned out that the default Archive Utility on MacOS was the culprit. If you're on a Mac, try unzipping with The Unarchiver or Keka instead.

**Comment by pat931** [comment]
@JarrettWendt Thank you so much for the advise. I did a quick test on my Mac, and found the sounds work on my Mac after using The Unarchiver app with the 7z files. Before I was using the default Archive Utility. I'll push the new sound to my printer later, but I can verify the sounds are no longer broken and this fix works, as far as Mac goes.

**Comment by InsanityAutomation** [comment]
> 
> 
> I had this problem and it turned out that the default Archive Utility on MacOS was the culprit. If you're on a Mac, try unzipping with The Unarchiver or Keka instead.

Ive never seen a rhyme or reason to this one and could never reproduce it here, so thats a good find! I dont have a mac at all here.

**Comment by clue3030** [comment]
So how do we fix the sound from being broken. I have the same issue where the sound is broken and making strange sounds when I press something and the sound resets when I power back on. How do I fix this issue please.

**Comment by InsanityAutomation** [comment]
The only things I have seen cause it were corrupted archives or poor SD cards. In every instance ive dealt with, or tinymachines reported from their facility, a fresh download extracted to a good SD card has resolved it. Locally ive only seen it occur from a corrupted archive, happened once when downloaded over a cellular connection. Tinymachines was working with a mac and saw it occasionally, but moving to a new SD card resolved it. In one case, the same SD card flashed a dozen machines, started corrupting sound on every one after that, new sd card flashed 100 more without an issue. Unfortunately thats about all of the guidance i can see on the issue outside of having one repeatably exhibiting it in front of me.

**Comment by quarky42** [comment]
The only thing I have to add is a question: What utility are you using to extract the file?

Without being sure what operating system you're using: Can you try the latest version of 7-zip?  (That is what I've been using.)

**Comment by clue3030** [comment]
I’m using a MacBook Pro 16”. I download the file and the Mac automatically unzips the file for me. I copy the diwin file to SD card and install it on the lcd

**Comment by clue3030** [comment]
I also have a pc I could use (surface pro 7).

**Comment by InsanityAutomation** [comment]
Sounds like the situation is exactly the same as what @JarrettWendt reported then, he reliably proved the Mac archiver was at fault in his case. The PC would be a safe alternative with 7zip.
