### ISSUE TITLE
Recommended firmware for stock Ender 5 plus?

### ISSUE THREAD

**Issue by pedromartinez11** [InsanityAutomation/Marlin#118]
Which firmware file(s) are recommended for stock ender 5 plus ?
http://insanityautomation.com/Firmware/Creality/
I want to use bilenear bed leveling (if recommended)

is the stock Ender5 plus "dual z"?

I think i narrowed it down to one of these:
```
E5P_BILH_DW6.hex.gz      // hemera? cuz 'H' ?
E5P_BIL_DW6.hex.gz       // screen? 
E5P_BIL_DZH_DW6.hex.gz   // dual z? hemera, cuz 'H' ?
E5P_BIL_DZ_DW6.hex.gz      // dual z?
```

I looked at the abbreviations here https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin_2.0

Solution is here: https://github.com/Jbchow/Marlin-Ender-5-Plus#jbchow-ender-5-plus-version

**Comment by Jbchow** [comment]
I went through this over the last 2 weeks ago! Let see if I can help. 

That is the stable branch. I would start there If you have a stock Ender 5 plus with a V2.2 board you should choose either of these 2 options.

Bi-linear Bed Leveling:
`E5P_BIL_DW6.hex.gz`

OR

Unified Bed Leveling (What I chose)
`E5P_UBL_DW6.hex.gz`

Notes:
If you have V2.2 of Creality you do not have a silent board.

DZ: Dual Z means it uses the E1 and the Z to drive each stepper separately. 
Both Z are on the same stepper driver.If you are on the V2.2 board the E1 (seconder extruder) stepper driver is not populated on the board.  You do not want this option.

Update Screen Firmware: the Bleeding branch has a working screen config! `https://github.com/InsanityAutomation/Marlin/blob/CrealityDwin2.0_Bleeding/CR-XABL_Screens_V2Rev2.7z `

Format sd card that came with printer to fat32 4k sectors (apparently it wont work if its not 4k sectors). copy the contents of the zip (DWIN_SET folder should be in the root of the sd card if this is done correctly) now remove the bottom cover from the printer plug in the sd card and wait till the top line says done. now remove the card and reboot the printer. Note: This version is designed for EXUI so it will not work with factory firmware.) 

To use UBL
UBL code:
Run to setup UBL: this will heat up bed and then probe bed for UBL then save to slot 1. I always level my bed fully before running this.

`M190 S60 ;Set Bed to 60c`
`G28 ; Home Printer`
`G29 P1 ;Runs Automatic Bed Leveling (UBL)`
`G29 P3 ;Extrapolates the leveling to parts the probe cannot reach.`
`G29 F10 ; Sets fade height to 10 mm`
`G29 S1 ; save bed topology to slot 1`
`G29 A ;ensures UBL is activated`
`@BEDLEVELVISUALIZER`
`G29 L1 ;Loads Mesh #1`
`M500 ;Saves settings to EEPROM `
`M140 S0 ;Turn-off bed`
`@BEDLEVELVISUALIZER`
`G29 T`

add to slicer:
In start g code find G28 and after that line add this

`G29 A ;activates UBL`
`G29 L1 ;loads UBL slot 1`
`G29 J; does a 3 point tilt correction on bed level`
`M420 S1 Z2 ;Enable ABL using saved Mesh and Fade Height`

**Comment by boggisthecat** [comment]
Hi.

I have tried to install the update for the display, and it bombed out part-way through and now just displays red diagonal lines when powered up.

It won't attempt to install from the SD card any longer, so I assume the bootloader got borked.

Any ideas on how to reflash these?

Thanks.

> Update Screen Firmware: the Bleeding branch has a working screen config! `https://github.com/InsanityAutomation/Marlin/blob/CrealityDwin2.0_Bleeding/CR-XABL_Screens_V2Rev2.7z `
> 
> Format sd card that came with printer to fat32 4k sectors (apparently it wont work if its not 4k sectors). copy the contents of the zip (DWIN_SET folder should be in the root of the sd card if this is done correctly) now remove the bottom cover from the printer plug in the sd card and wait till the top line says done. now remove the card and reboot the printer. Note: This version is designed for EXUI so it will not work with factory firmware.)

**Comment by InsanityAutomation** [comment]
You would need to use the DGUS toolbox to flash over serial directly by plugging a PC adapter into the serial port on the display.

https://github.com/juliandroid/DWIN_CR_10s_Pro

I have not performed the procedure, as I have yet yo have a failure here and nobody has sent me a failed screen yet.

**Comment by boggisthecat** [comment]
Hi.

Thanks for the pointer.  I can't find a PC with a hardware serial port, so some improvisation may be required.  If I can get this to work I will post up how.

Here is a photo of the display at present:

![20200412_112023_mod](https://user-images.githubusercontent.com/63491774/79057444-bc66cd00-7cb5-11ea-8ea5-c785a980d891.jpg)

**Comment by boggisthecat** [comment]
Hi again.

A fruitless few hours trying to reflash this.  I think the bootloader is borked.

This is the wiring:
![20200412_220646_mod](https://user-images.githubusercontent.com/63491774/79066265-cf57bc80-7d0a-11ea-8c55-0ce86fbf49d1.jpg)

It basically stays stuck, not acknowledging the boot command:
![Serial_comms_OK](https://user-images.githubusercontent.com/63491774/79066453-1b573100-7d0c-11ea-8f75-b794c9a2819c.png)
![20200412_221838_mod](https://user-images.githubusercontent.com/63491774/79066495-725d0600-7d0c-11ea-8985-67eba370fe40.jpg)

Also, the comms is doing a weird echo, with no power to the DWIN board, if you don't have GND connected:
![Serial_comms_bugged](https://user-images.githubusercontent.com/63491774/79064286-bf84ac00-7cfb-11ea-8d9e-a0ba0c9fbb79.png)

I checked both the RX2/TX2 and RX4/TX4 pairs, and without the GND to serial it does this regardless.  This is why there is the weird double ground pin to the serial (it also doesn't want to share the ground if forked before the board pin).

The Targus breakout box I am using is pretty dodgy.  Some nice 118 Vac sitting on the 'grounded' surfaces.  Tingley.

**Comment by boggisthecat** [comment]
Also, some info that may or may not be useful.

Unknown boot chip (presumed borked):
![20200412_183124_mod](https://user-images.githubusercontent.com/63491774/79066566-0af38600-7d0d-11ea-91f0-4a9f2e2a516e.jpg)

DWIN branded mystery chip:
![20200412_182736_mod](https://user-images.githubusercontent.com/63491774/79066565-07f89580-7d0d-11ea-8dc9-158532ecf726.jpg)

My board had some interesting stuff on it:
![20200412_193825_mod](https://user-images.githubusercontent.com/63491774/79066675-f368cd00-7d0d-11ea-9c12-fa1a9d07df21.jpg)

**Comment by boggisthecat** [comment]
Well... derp.

Probably shouldn't have looked at the wiring cables shown in the manufacturer's documents and assumed that they were wiring straight to a serial header.

Aside from the inverted logic, the voltage levels would be way out of spec for this device.  So it may not have been completely borked before, but probably is now.

(Retested everything with a TTL-RS232 converter this time.  Ugh.  Well, time to buy a new board.)

**Comment by pedromartinez11** [comment]
> I would start there If you have a stock Ender 5 plus with a V2.2 board you should choose either of these 2 options.

@Jbchow
My 5+ came with a 2.1 board. Would your steps still work?

EDIT: I was too eager, and I went ahead and followed your steps :). The screen and mainboard appear to be flashed successfully.

While running your leveling gcode (from SD), I noticed that each probe doesn't "click" https://photos.app.goo.gl/yqg6bCcTpf5TVo5H7

Is this normal?

**Comment by Jbchow** [comment]
Should be good. the "silent board" uses different stepper drivers.
 `//#define CrealitySilentBoard // Creality board with TMC2208 Standalone drivers. Disables Linear Advance
The build listed in my post above runs the "A4988" stepper drivers (google tells me both 2.1 and 2.2 use these chips)

Also note this build has filament runout commented out (it comes from marlin head from what I can tell) Glad I tested it before I needed to use it. 

Clicking - That is normal. it only "Clicks" when it turns the probe into an idle state. UBL just leaves it out during all the probes.  - I printed a "bltouch shield" from thingaverse to protect the bltouch tip from crashes.

My config has it turned on. I am debating uploading my config to github. I tuned everything for the ender 5 plus I have. If you would find this useful let me know!

**Comment by pedromartinez11** [comment]
@Jbchow 
>  I am debating uploading my config to github

Yea please! It would be very useful for me. 
Can you upload a gist of the git diff / patch?

**Comment by Jbchow** [comment]
Here you go: https://github.com/Jbchow/Marlin-Ender-5-Plus/tree/CrealityDwin2.0_Bleeding-E5P-jbchow-Only
I had issues with the bleeding branch and printing off the sd card. I only wanted to print from the sd card to remove printing artifacts from buffer issues on octoprint. I found out about Melzi Host which disables  the sd card to allow for a larger buffer for octoprint.

**Comment by pedromartinez11** [comment]
> Here you go: https://github.com/Jbchow/Marlin/tree/CrealityDwin2.0_Bleeding-E5P-jbchow-Only
> I had issues with the bleeding branch and printing off the sd card. I only wanted to print from the sd card to remove printing artifacts from buffer issues on octoprint. I found out about Melzi Host which disables the sd card to allow for a larger buffer for octoprint.

thank you @Jbchow ! Are you using the "bleeding" screen with that config? (https://github.com/InsanityAutomation/Marlin/blob/CrealityDwin2.0_Bleeding/CR-XABL_Screens_V2Rev2.7z)

**Comment by Jbchow** [comment]
@pedromartinez11 Yes! It works awesome.
I also made a wiki page with the steps from above: https://github.com/Jbchow/Marlin-Ender-5-Plus/wiki/Update-Screen-Firmware:-the-Bleeding-branch-has-a-working-screen-config
My Cura settings are in the read me section

**Comment by pedromartinez11** [comment]
thank you @Jbchow it's working great! Closing this issue
