### ISSUE TITLE
Auto leveling at the beginning of printing 

### ISSUE THREAD

**Issue by mateo356** [InsanityAutomation/Marlin#123]
Hi everyone,

I found a little issue with auto leveling, If I enable auto leveling in tab Leveling mode, Auto leveling should be done at the beginning of each printing, correctly? But it doesn't happen 

I uploaded 10SPro_BLT_BIL_DW6.hex file ( fbfca0b )
 
![64_E_BedLeveling](https://user-images.githubusercontent.com/47969320/79307143-bad81780-7ef6-11ea-9943-f2dad570142f.jpg)

**Comment by masc2279** [comment]
There is a much simpler way Just add a G29 to your start script and it all works perfect .... Most if not all slicers allow you to add a start script.

**Comment by masc2279** [comment]
I tested this also on my machine and I can confirm that it does not work CR-10 MAX. But as i posted above just use a G29 which is a work around.

**Comment by mateo356** [comment]
Yes, I putted G29 and M500 at the beginning of G code, without M500 just done auto bed leveling without saving those value.

**Comment by elecktron3d** [comment]
i have those two gcodes on the Start GCode Section.

G28 ;Home
M420 S1 Z2 ;Enable ABL using saved Mesh and Fade Height

Do you recommend to change those gcode to:
G29
M500

**Comment by mateo356** [comment]
Hi, 
I'm using Cura for generating g-code, and If you want auto bed leveling at the beginning the 3d print you need to put two those g-code line  after G28 and before M420 S1 Z2, look image in attachment.
![image](https://user-images.githubusercontent.com/47969320/83599242-f80e6c80-a56b-11ea-93bc-47f39b2feea2.png)

**Comment by elecktron3d** [comment]
@mateo356 thank a lot! ill try it

**Comment by elik745i** [comment]
I'm using Creality CR-10 MAX and I can't disable auto bed leveling through menu, does not work DW6.2 not  in DW7 why? Everything was working on original CR-10 MAX firmware...

**Comment by InsanityAutomation** [comment]
The standard process is to recall the mesh from the EEPROM at the start of each print rather than reprobing. Reprobing constantly brings in a large margin of error. Its considered best practice to probe once and store a good validated mesh and restore it. It is currently configured to enable leveling if there is a valid mesh on startup.
