### ISSUE TITLE
error compiling with #define DISTINCT_E_FACTORS for CR10s PRO

### ISSUE THREAD

**Issue by Baltojikale** [InsanityAutomation/Marlin#126]
Hello,
Struggling for few days compiling fw. For printer creality CR10s PRO  wanted to enable second stepper using dual bowden spliterY. My additional motor has different steps/mm setting that ones originally installed on CRs PRO.  Tried compiling with almost all Marlin 2.0.x versions that are pined in this fork  (Creality_DWINTest; Creality_Marlin2.0.x; CrealityDwin2.0_Bleeding and so on...) After enabling  #define DISTINCT_E_FACTORS in Configuration.h  always get error  on declaration of additional axis  

> In file included from c:\users\eivyd\appdata\local\temp\arduino_build_34340\sketch\src\inc\marlinconfigpre.h:47:0,
 from sketch\src\lcd\extui\ui_api.cpp:44:
sketch\src\lcd\extui\ui_api.cpp: In function 'void ExtUI::setAxisSteps_per_mm(float, ExtUI::extruder_t)':
sketch\src\lcd\extui\ui_api.cpp:589:49: error: 'axis' was not declared in this scope
planner.settings.axis_steps_per_mm[E_AXIS_N(axis - E0)] = value;
                                           ^
c:\users\eivyd\appdata\local\temp\arduino_build_34340\sketch\src\inc\Conditionals_LCD.h:508:41: note: in definition of macro 'E_AXIS_N'
   #define E_AXIS_N(E) AxisEnum(E_AXIS + E)
                                         ^
sketch\src\lcd\extui\ui_api.cpp:589:49: note: suggested alternative: 'axis_t'
 planner.settings.axis_steps_per_mm[E_AXIS_N(axis - E0)] = value;
                                                 ^
c:\users\eivyd\appdata\local\temp\arduino_build_34340\sketch\src\inc\Conditionals_LCD.h:508:41: note: in definition of macro 'E_AXIS_N'
   #define E_AXIS_N(E) AxisEnum(E_AXIS + E)
                                         ^
sketch\src\lcd\extui\ui_api.cpp: In function 'feedRate_t ExtUI::getAxisMaxFeedrate_mm_s(ExtUI::extruder_t)':
sketch\src\lcd\extui\ui_api.cpp:598:56: error: 'axis' was not declared in this scope
     return planner.settings.max_feedrate_mm_s[E_AXIS_N(axis - E0)];
                                                        ^
c:\users\eivyd\appdata\local\temp\arduino_build_34340\sketch\src\inc\Conditionals_LCD.h:508:41: note: in definition of macro 'E_AXIS_N'
   #define E_AXIS_N(E) AxisEnum(E_AXIS + E)
                                         ^
sketch\src\lcd\extui\ui_api.cpp:598:56: note: suggested alternative: 'axis_t'
     return planner.settings.max_feedrate_mm_s[E_AXIS_N(axis - E0)];
                                                        ^
c:\users\eivyd\appdata\local\temp\arduino_build_34340\sketch\src\inc\Conditionals_LCD.h:508:41: note: in definition of macro 'E_AXIS_N'
   #define E_AXIS_N(E) AxisEnum(E_AXIS + E)

Does anyone know how to solve this axis declaration problem ?

**Comment by InsanityAutomation** [comment]
Basically youll need to mix some CRX and CR10SPro things. Enable CRX instead of pro then change esteps.
