### ISSUE TITLE
Linear Advance Ender 5 plus Silent board

### ISSUE THREAD

**Issue by eseuveeme** [InsanityAutomation/Marlin#127]
Trying to calibrate Linear Advance on Ender 5 plus Silent Board Hemera.hex but it seems like it's dissable.
All K factor gcode are printed equals

****
SENDING:M900
echo:Unknown command: "M900"
****

**Comment by InsanityAutomation** [comment]
With the silent board, the TMC drivers are in standalone mode and therefore not compatible with linear advance. The step rate changes caused by injected steps will cause a stealthchop mode driver to go into shutdown.
