### ISSUE TITLE
Ender 5 Plus bed size in autobuilt hex file

### ISSUE THREAD

**Issue by jxlarrea** [InsanityAutomation/Marlin#128]
A couple of days ago I installed the firmware for my Ender 5 Plus (with silent board) located at [https://github.com/InsanityAutomation/Marlin/blob/CrealityDwin_2.0/Hex%20Files/E5P_UBL_Slnt_DW6.hex.gz](https://github.com/InsanityAutomation/Marlin/blob/CrealityDwin_2.0/Hex%20Files/E5P_UBL_Slnt_DW6.hex.gz). 

I noticed that the bed size is specified as 360x360 instead of 350x350. Is this a mistake or is there a particular reason for this discrepancy?

**Comment by jxlarrea** [comment]
It seems like having the bed size larger than the physical bed causes the probe to crash against the frame by a few millimetres (~5mm) when the X position is set to 0 using the Move menu on the touchscreen.

It also causes the probe to crash really hard against the frame when using the "validate mesh" button on the Aux leveling screen.

**Comment by jxlarrea** [comment]
Is there any value I can modify on the Configuration.h file to avoid the probe crashing against the frame?

**Comment by cuboy29** [comment]
try to relocate the x end switch.

**Comment by Uforias** [comment]
This link will help you changing the values on configuration.h: https://reprap.org/wiki/Configuring_Marlin_Bed_Dimensions

**Comment by jxlarrea** [comment]
I ended up changing the bed dimensions in the `Configuration.h` file. I'm just wondering why is the Ender 5 Plus bed size defined as 360x360 instead of 350x350 on this firmware. Is it a typo or is there any purpose to it? Something to do with UBL perhaps?

**Comment by cuboy29** [comment]
i noticed the size is also 360 in the source that Creality just released for the printer as well.

**Comment by bpivk** [comment]
Because the actual bed size is in fact 370(Y)x376(X).
The stock firmware's build plate size is defined at 360x360mm due to the clips.
