### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by jimmyeao** [InsanityAutomation/Marlin#130]
### Description

Unable to compile

### Steps to Reproduce

Edit configuration.h for stocker ender 5 plus and bltouch
Compile
**Expected behavior:** [What you expect to happen]
FW compiles

**Actual behavior:** [What actually happens]
hundreds of errors and it seems to be compiling for every option possible

#### Additional Information
[Configuration_adv.zip](https://github.com/InsanityAutomation/Marlin/files/4535312/Configuration_adv.zip)

I cant find any documentation on how to correctly configure this package for a stock Ender 5 plus (or any other machine)
Im not new to vscode, or Marlin, but I seem to be missing something here.

My goal is to update the stock board so I can use M500 (and linear advance if space), and to then compile for an SKR1.3 and TMC2209 which I have coming.

Any pointers gratefully received :)

**Comment by cuboy29** [comment]
Don't edit the configuration.h

Compile using these profiles.  I just edit platformio.ini instead.

<img width="479" alt="Screen Shot 2020-04-26 at 8 00 03 AM" src="https://user-images.githubusercontent.com/13719808/80311347-0d85bf00-8794-11ea-9202-1ebf9a350cf9.png">

**Comment by jimmyeao** [comment]
so I just delete anything I don't want under default_envs=  (Leaving E5P_BIL)?

**Comment by cuboy29** [comment]
you don't have to delete anything.  just click on build button for the E5P_BIL only and it'll just compile for that version.

**Comment by jimmyeao** [comment]
got it, thanks. Not seen it used like that before :)
