### ISSUE TITLE
Ender 5 Plus Display on SKR1.3?

### ISSUE THREAD

**Issue by jimmyeao** [InsanityAutomation/Marlin#132]
### Description

I have managed to flash the screen with the CR-XABL_Screens_V2Rev2.7z firmware, and have the SKR1.3 working in the Ender 5 Plus, unsure how (or if) I can connect the original display to the SKR1.3?

**Comment by jimmyeao** [comment]
update. cut the lug off the connector and reversing the plug now brings the screen to life, but I have this 
![screen](https://user-images.githubusercontent.com/5197831/80573290-97819200-89f7-11ea-8e16-2d38c0ad6aa3.jpg)
Octoprint works fine

**Comment by cuboy29** [comment]
can you share you config files?  i am thinking of changing out my board to this too.  Might go with the TFT3.5 for now.

**Comment by jimmyeao** [comment]
https://deviousweb-my.sharepoint.com/:u:/p/jimmy/ERv4dS15uGlHon-RgYecZ68BULj_-5eNfssLpjIY7Wgp6g?e=V478fQ
Bear in mind, this contains the following changes to make it work with the E5+
![image](https://user-images.githubusercontent.com/5197831/80794009-a51e4f80-8b90-11ea-8070-902e578f6a0a.png)

This is an SKR1.3 with TMC2209s
<img width="1033" alt="Bildschirmfoto-2019-11-21-um-01 42 04" src="https://user-images.githubusercontent.com/5197831/80794112-f0d0f900-8b90-11ea-8d8d-46c3f3f54eba.png">

**Comment by cuboy29** [comment]
Thanks.. I want to try and install the SKR1.3 E3 version.

**Comment by InsanityAutomation** [comment]
If no data is getting to the screen, try swapping the TX/RX pins. Remember mobo TX goes to screen RX and so on.

**Comment by jimmyeao** [comment]
Success! Made my own cable and connected to the TFT header on the SKR, now all working.
