### ISSUE TITLE
CR10S Pro - Shouldn't CHOPPER_DEFAULT_24V instead of CHOPPER_DEFAULT_12V be set?

### ISSUE THREAD

**Issue by chunter1** [InsanityAutomation/Marlin#135]
Shouldn't in the CR10S Pro configuration CHOPPER_DEFAULT_24V instead of CHOPPER_DEFAULT_12V be set?

**Comment by InsanityAutomation** [comment]
Totally irrelevant without alot of work to solder uart to the board. It isnt used otherwise.
