### ISSUE TITLE
Critical design flaw on CR10S Pro mainboard connections to TMC2208

### ISSUE THREAD

**Issue by chunter1** [InsanityAutomation/Marlin#137]
While i was reverse engineering the TMC2208 connections on the CR10S Pro mainboard (Creality v2.4) to wire the UART pin to the Atmega, i found the following design flaw.
All three pins, the PDN_UART, INDEX and DIAG are connected together and pulled up to +5V by a 100k resistor.
The problem with this connection ist that the outputs of the INDEX and DIAG pins are working against eachother and additionally present a varying critical voltage level to the PDN_UART pin.
The resulting high-level is around 2.7 V only!
Luckily the level seems to be still high enough to not force the chip into power down via the PDN_UART pin!

I managed to mod the board to at least disconnect the PDN_UART pin and connect it to the Atmega.
That way, i can now control the TMC2208 of the extruder to hopefully make linear advance an option on my CR10S pro. :)

**Comment by InsanityAutomation** [comment]
While its great info, im clearing out the inactive issues, and the machine is old enough this doesnt really need to sit open for visibility anymore.

Thanks
