### ISSUE TITLE
Remove configs.

### ISSUE THREAD

**Issue by joleeee** [InsanityAutomation/Marlin#142]
### Description

I thought you had to get the configs from the link in the config/README.md file. Perhaps it should be deleted? Ill do a PR later today.

**Comment by InsanityAutomation** [comment]
Each rebase would end up just bringing it back. With the precompiled hex files getting expanded with every build, less and less people will go near the source over time. I probably will add a note to point out that you only need to look at the existing config file in the readme on the base page.
