### ISSUE TITLE
Trying to use for CreatBot

### ISSUE THREAD

**Issue by ModMike** [InsanityAutomation/Marlin#144]
I would like to use this branch with a Creatbot. It uses a DWIN DMT48270M043_02WT.

I created a pin file and everything works except the screen. What screen firmware would you recommend for dual head machine with no auto level? I do need load and unload for both extruders.

Thanks!

**Comment by InsanityAutomation** [comment]
The CRX stock screens should be close. May need to check OS version on the panel itself to see if needs modified screen change commands like advi uses. They run the prior generation dwin firmware on the screen itself.

**Comment by dragonpaco** [comment]
> 
> 
> I would like to use this branch with a Creatbot. It uses a DWIN DMT48270M043_02WT.
> 
> I created a pin file and everything works except the screen. What screen firmware would you recommend for dual head machine with no auto level? I do need load and unload for both extruders.
> 
> Thanks!

Did you ever get Marlin working correctly on the creatbot dx? Creatbot is refusing to share their code and the lcd/usb issue is not worth the benefits of BLtouch.  

Thanks

**Comment by ModMike** [comment]
I did get ti working somewhat using a Frankenstein version. The screen partially works but code needs to be gone through to make all the commands work.

I don't even remember what I did.

**Comment by InsanityAutomation** [comment]
Get someone to send me one and ill make it run lol

**Comment by ModMike** [comment]
Whats your shipping address? I would like nothing more than to stick it to them by releasing the firmware afterwards.

**Comment by InsanityAutomation** [comment]
Shoot me an email - d.menzel@insanityautomation.com

**Comment by InsanityAutomation** [comment]
FYI, current screen builds add manual mesh leveling for DW74 and may just work as is...

**Comment by InsanityAutomation** [comment]
Never heard more on Creatbot or got one. Closing
