### ISSUE TITLE
Homing causes collision at high Z values - CR10 Max

### ISSUE THREAD

**Issue by todd-herbert** [InsanityAutomation/Marlin#145]
### Description

When homing on Creality CR-10 Max, X is first decreased until the print-head makes contact with a stop switch mounted on the extruder. If this takes place at high Z values, the print-head strikes the pull-rod supports before it can reach the stop switch.

### Steps to Reproduce

1. Raise print head to near top of build envelope (Z = ~470)
2. Run "Auto-Home" from LCD Menu (or alternatively, issue G28 via USB)

**Expected behavior:** Print-head moves left, to X=0, collides with stop switch. Printer then continues with leveling routine by moving bed towards Y=0

**Actual behavior:** Print-head moves left, towards X = 0, strikes diagonal pull-rod supports. Motors continue to run, attempting to move the print-head towards the stop-switch it is unable to reach.

#### Additional Information

* Build is CR10Max_BIL_DW6.2

* Creality marketing image demonstrating the pull-rods:

![CR-10-Max-_3](https://user-images.githubusercontent.com/24772776/85202318-aa5e7600-b359-11ea-938d-6d85b98f2e60.jpg)

**Comment by InsanityAutomation** [comment]
Unfortunately due to the mechanical design, this is unavoidable. We did remove the home action from the finish print button in the development branches, which will be in the next tagged bundle tomorrow.
