### ISSUE TITLE
bug with the M125 "pause" function

### ISSUE THREAD

**Issue by thsrp-bob-roger** [InsanityAutomation/Marlin#146]
Hello, for information and as a reminder because the bug has already been reported. The "Park_Head_Pause (M125) function is corrupted despite sharing its settings with the Change_Filament (M600) function which works without problems. I hope and I think this function (M125) will work correctly in the next update ... ( DW6.3) Thank a lot

**Comment by InsanityAutomation** [comment]
As this has been largely redone, and even further improved in the 7.4 update thats in final testing, im closing the older M600/M125 issues. If this is still relevant, please reopen the issue.
