### ISSUE TITLE
Migrate Creality_DWIN.cpp to use DGUSDisplay.cpp

### ISSUE THREAD

**Issue by yufanyufan** [InsanityAutomation/Marlin#148]
### Description

DGUSDisplay.cpp and Creality_DWIN.cpp both handles DWIN LCD. DGUSDisplay is from Marlin trunk.
Merging them makes future development easier for both branches.

**Comment by InsanityAutomation** [comment]
This is older, and drastically different. This is intended to still function with the stock creality display and is lighter weight. Same could be said for the i3 mega and duplicator machines as technically its the same hardware. Same for the Ender 3 V2 as its the same hardware. Drastically different implementations for the same hardware already in head.
