### ISSUE TITLE
Cr10s pro shut down recovery still dosent work

### ISSUE THREAD

**Issue by Nicolozano97** [InsanityAutomation/Marlin#149]
I´ve been trying the lastest firmware for the cr10s pro with bil and the shut down recovery dosn´t work, I always lost the print with the new version. i will be gratefull if you can solve it.  I have the lastest screen firmware too.

**Comment by mrbipbip** [comment]
Also the same issue here. Since Marlin 2.0 (with the stable branch too).

**Comment by InsanityAutomation** [comment]
Please keep in mind it is included but disabled by default due to reported crashes with many SD cards. If you want to have PLR active for youre print, youll need M413S1 in youre starting gcode. If the printer reboots immediately after starting a print, use a different SD card.
