### ISSUE TITLE
DW7 - Serial Port (Pronterface) connection not working

### ISSUE THREAD

**Issue by Frontier314** [InsanityAutomation/Marlin#162]
### Description

DW7 version of CRX_NoFil_DW7 cannot connect to Pronterface.
Upon opening the connection, the serial port displays "External reset" and it is not possible to issue g-Code commands.

### Steps to Reproduce

1. Install CRX_NoFil_DW7
2. Connect to the CRX via Pronterface on COM port speed 250000
3. Issuing any g-Code command, Pronterface responds "[ERROR] Printer is not online." Pronterface "CONNECT" button does not change to "DISCONNECT" meaning that the USB serial connection is closed.

**Expected behavior:** [What you expect to happen]

To be able to connect to printer console via Pronterface and issue g-Code commands, as I could do with DW6.2.

Connection to DW6.2 via Pronterface
`
Connecting...
start
Printer is now online.
echo: External Reset
Marlin 2.0.5_DW6.2
echo: Last Updated: 2020-04-30 | Author: TinyMachines3D
echo:Compiled: May  4 2020
Using tool 0.
echo: Free Memory: 1433  PlannerBufferBytes: 832
==Dwin Init Complete==
Received command TM3D CR-X Ready.
//action:notification TM3D CR-X Ready.
==onLoadSettings==
echo:V77 stored settings retrieved (806 bytes; crc 3232)
==onConfigurationStoreRead==
 init zprobe_zoffset = 0.00
//action:prompt_end
echo:SD card ok
echo:Active Extruder: 0
ok P7 B3
  startprogress
>>> M503
SENDING:M503
echo:  G21    ; Units in mm (mm)
echo:; Filament settings: Disabled
echo:  M200 D1.75
echo:  M200 T1 D1.75
echo:  M200 D0
echo:; Steps per unit:
echo: M92 X80.00 Y80.00 Z400.00 E95.00
echo:; Maximum feedrates (units/s):
echo:  M203 X500.00 Y500.00 Z10.00 E75.00
echo:; Maximum Acceleration (units/s2):
echo:  M201 X1500.00 Y1500.00 Z100.00 E75.00
echo:; Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
echo:  M204 P750.00 R1000.00 T300.00
echo:; Advanced: B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>
echo:  M205 B20000.00 S0.00 T0.00 J0.06
echo:; Home offset:
echo:  M206 X0.00 Y0.00 Z0.00
echo:; Mesh Bed Leveling:
echo:  M420 S0 Z0.00
echo:; PID settings:
echo:  M301 P19.00 I1.40 D66.00
echo:  M304 P690.34 I111.47 D1068.83
echo:; Power-Loss Recovery:
echo:  M413 S0
echo:; Linear Advance:
echo:  M900 T0 K0.00
  M900 T1 K0.00
echo:; Filament load/unload lengths:
echo:  M603 T0 L450.00 U430.00
echo:  M603 T1 L450.00 U430.00
echo:; Tool-changing:
echo:  M217 S80.00 E2.00 P3000.00 R3000.00 X315.00 Y10.00 Z2.00
ok P7 B2
Disconnected.
`

**Actual behavior:** [What actually happens]

Immediately upon clicking "CONNECT", the connection is closed via external reset.

Connection by Pronterface on DW7
`
Connecting...
echo:start
 External Reset
Marlin 2.0.6_DW7
echo: Last Updated: 2020-08-10 | Author: TinyMachines3D
echo:Compiled: Sep 25 2020
echo: Free Memory: 1362  PlannerBufferBytes: 832
==Dwin Init Complete==
Received command TM3D CR-X Ready.
//action:notification TM3D CR-X Ready.
==onLoadSettings==
echo:V81 stored settings retrieved (826 bytes; crc 24101)
==onConfigurationStoreRead==
 init zprobe_zoffset = 0.00
//action:prompt_end
echo:SD card ok
  startprogress
>>> M503
[ERROR] Printer is not online.
`

**Comment by LMS0815** [comment]
same issue see: https://github.com/InsanityAutomation/Marlin/issues/154

**Comment by InsanityAutomation** [comment]
Closing as duplicate
