### ISSUE TITLE
Help translating Creality Dwin to Arabic

### ISSUE THREAD

**Issue by AmrBarghouthi** [InsanityAutomation/Marlin#163]
I want to translate Marlin to Arabic well eventually I want to add to All possible screens but for now I want to start with Creality  CR 10s pro and it's variants because those the printers I have and a printer with graphical display is probably going to be easer to translate to Arabic   

my problem is I found no documentation on how to generate the DWIN_SET files 
and also what files do I need to change in marlin if any  

note: Arabic is written from right to left so I need to flip the GUI which means  the buttons are not going to be in the same place as in English, which means the touch events needs be modified when in Arabic

**Comment by InsanityAutomation** [comment]
The majority of it is all in the graphics. The rest of the strings are fed from the Marlin firmware, so any supported language will update a good portion of the messages. As for reorganizing the buttons, unfortunately thats not something we would have time to maintain going forward. It would mean every version we need to build another revision. Its time consuming enough with the 3 there are now. If it was done through just the language options in marlin and the graphics files, we could keep it maintained however its not feasible to keep maintaining additional touch configurations for other languages.
