### ISSUE TITLE
CrealityDwin_2.0 UI goes chinese after successful print. Machine needs reboot to print again. 

### ISSUE THREAD

**Issue by Ericvf** [InsanityAutomation/Marlin#165]
After a print completes successfully the UI becomes Chinese. Changing it back to English doesn't help, the UI doesn't respond to a lot of commands. I need to cycle the printer in order to get it working again. 

### Steps to Reproduce

1. Clone the repo, my branch is the CrealityDwin_2.0
2. Uncomment compiler directive "PLUS" since I use a CR-10s Pro.
3. Compile and flash
4. Print any file from SD card

**Actual behavior:** 

The print succeeds. It executes the ending G-code. Shows Chinese prompt that the print was successful. Press OK and print another file. UI doesn't respond to the "Print" button. 

**Expected behavior:** 

The print succeeds. It executes the ending G-code. Shows English prompt that the print was successful. Press OK and try printing another file.

**Comment by Crash416** [comment]
I am having this same issue... has there been any update or fix?

**Comment by Ericvf** [comment]
Not that I know of. I'm still having this issue. It doesn't happen for every print but it does keep happening. Very annoying.

**Comment by InsanityAutomation** [comment]
Can you confirm if you see this in the current builds? I have not reproduced it here.

**Comment by clue3030** [comment]
I had this issue on my Ender 6 but it clears up on it’s on in less than a second.
