### ISSUE TITLE
SKR1.4T bltouch not working, issue solved but please update for others.

### ISSUE THREAD

**Issue by Gamer9House** [InsanityAutomation/Marlin#170]
https://github.com/InsanityAutomation/Marlin/blob/12e230ca30172d65fe6835432a884a36ee4abf67/Marlin/Configuration.h#L1557

Hi, not a programmed nor marlin expert so this took me quite a long time to figure out xD
anyway, as SKR1.4 boards have dedicated z-prob pins this line should have if-clause when you are using the original Creality board or SKR/any other board that has dedicated pins.

z prob pins would not work when this is active.

Thank you all for the builds, they are super helpful, especially for noobs like myself.

**Comment by InsanityAutomation** [comment]
We typically default all installations to use the ZMin pin to simplify installation instructions across all machines. This also leaves the additional probe pin open for other functions, such as case lights, if desired.
