### ISSUE TITLE
cr10s pro v2 dw7 139c bed temp

### ISSUE THREAD

**Issue by mastav79** [InsanityAutomation/Marlin#171]
### Steps to Reproduce

1. [Meaure 2 times]
2. [wait for e heating for z offset]
3. [if you dont change z offset right away the bed temp seems to rise indefinately]

**Expected behavior:** [I expect the bed to stop at 60c]

**Actual behavior:** [The bed temp rises indefinitely]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by InsanityAutomation** [comment]
Have you ensured there is not an electrical issue with the SSR controlling the bed?
