### ISSUE TITLE
error: no include path  in which to search for limits.h

### ISSUE THREAD

**Issue by Noirad** [InsanityAutomation/Marlin#175]
I'm not sure what's going wrong. I'm just trying to use CR-X and SRK1.4Turbo but keep getting compiling errors

Config code:

`/*
   Basic Options

   Select Machine
*/

// Standard Atmega2560 machines (No bootloader required)

//#define MachineEnder5Plus
//#define MachineEnder4
//#define MachineCR20 //Buzzer doesnt work
//#define MachineCR20Pro
//#define MachineCR10S
//#define MachineCR10SV2
//#define MachineCR10SPro // Graphics LCD Requires soldering R64 and R66
//#define MachineCR10SProV2 // Second Gen 10S Pro with BLTouch wired to Z Max
#define MachineCRX
//#define MachineCRXPro
//#define MachineCR10Max
//#define MachineS4
//#define MachineS5
//#define MachineCR2020 // Industrial Series 2020

// Atmega1284P machines Needs a bootloader flashed before installation
// See video here : https://www.youtube.com/watch?v=fIl5X2ffdyo

//#define MachineEnder2
//#define MachineEnder3
//#define MachineEnder5
//#define MachineMini
//#define MachineCR10

//STM32F103RE Machines
//#define MachineEnder3V2
//#define MachineEnder3Pro422
//#define MachineEnder3Pro427

//#define PLUS // Adds bltouch, allmetal, bilinear (standard), lerdge, 93 e steps/mm

/*
   Hotend Type
   Choose one option below.
   E3D assumes the following mount :
   https://www.thingiverse.com/thing:2494642

   Configured with 5015 left wing, right wing ABL sensor (BLTouch or M18) only

   Mosquito may be set with either mounting option above and overrides temp sensor and max temp
   E3D Mounting assumes Groovemount
   Creality Mounting assumes bolt-on kit
*/
//#define HotendStock
//#define HotendE3D
//#define HotendMosquito

//Enable this if you have an all metal hotend capable of 300c
#ifndef HotendAllMetal
  #define HotendAllMetal
#endif

// Enable this if you used a plug and play creality e3d or mosquito kit and kept the Creality thermistor
//#define CrealityThermistor

/*
 * Select these if you have changed to a high performance extruder
 */

 //#define EZRstruder
 //#define Bondtech
 //#define E3DTitan
 #define E3DHemera
 //#define CrealityTitan
 //#define DDXExtruderKit

 //#define MicroswissDirectDrive
 //#define DirectDrive // Any direct drive extruder, reduces filament change lengths

/*
   Choose bed type below. If you have an extenrally controlled
   ac bed, leave both disabled
*/
//#define BedAC
//#define BedDC

//#define SolidBedMounts //Removed a few LCD options to save some memory since not needed with solid mounts

/*
   Choose ABL sensor type below
   Leave all disabled if no sensor is available
*/
//#define ABL_EZABL // TH3D EZABL or Any NO Sensor
//#define ABL_NCSW //Creality ABL or Any NC Sensor
//#define ABL_BLTOUCH
//#define ABL_TOUCH_MI // Uncomment ABL_TOUCH_MI to use Touch-MI sensor by hotends.fr

//#define CREALITY_ABL_MOUNT //Using creality ABL mount
//#define E3D_DUALFAN_MOUNT // Using HD Modular mount as above with 2 5015 blowers and sensor on the right
//#define E3D_PROBEMOUNT_LEFT // Default is probe mounted to the right for E3D. Set this to invert.

/**
 * Screen options
 */

//#define OrigLCD // Upgraded mainboard with single cable Ender LCD
#define GraphicLCD //Full graphics LCD for Ender 4, CR-X or CR10SPro
//#define Big_UI // Lightweight status screen, saves CPU cycles

// Touchscreen options - only 32 bit boards have the open serial ports to use with graphics displays above
//#define ForceCRXDisplay
//#define Force10SProDisplay

//#define AddonFilSensor //Adds a filament runout sensor to the CR20 or Ender 4
//#define lerdgeFilSensor //Using lerdge filament sensor, which is opposite polarity to stock
//#define DualFilSensors //Using dual filament sensors on XMax and YMAX
//#define FilamentEncoder //Using filamet jam sensor such as the Bigtreetech Encoder wheel

//#define PurgeBucket //Adds automatic wiping on tool change if purge bucket is installed

// Advanced options - Not for most users

// User defined thermistor
//Sets thermistor based calculated beta values instead of lookup tables
//#define ConfigurableThermistors

//#define CrealityViewerKit // Reduces baud to 115200 for Creality viewer kit

/*
   Choose bed leveling type here
   Requires a sensor from above
   Melzi board users may only select ABL_BI for bilinear leveling
   If a probe is enabled and nothing selected here, defaults to Bilinear
*/
//#define ABL_BI
//#define ABL_UBL

/*
   For melzi boards these options allow you to cusomize what you want to do.
   Since the storage space is so small, it cannot fit most options together.
   Even just a probe and leveling with standard options is filling te entire program space!
*/
//#define OrigLA // Enable this for linear advance instead of mesh leveling on a melzi board
//#define MelziHostOnly // Enable this to turn off local SD support and instead prioritize options for Octoprint or USB

/**
 * Advanced motherboard replacement options
 */

//#define OriginalCrealitySquareBoard
//#define MachineCR10Orig // Forces Melzi board
//#define Melzi_To_SBoardUpgrade // Upgrade Melzi board to 10S board
//#define CrealitySilentBoard // Creality board with TMC2208 Standalone drivers. Disables Linear Advance

//#define SKR13 // 32 bit board - assumes 2208 drivers
//#define SKR14
#define SKR14Turbo
//#define SKRPRO11

// This board is NOT recommended and is HIGHLY advised against utilizing the expanded builds for.
// The MCU is rated for 256kb and stability problems, including hangs with heaters on, have been reported.

//#define SKRMiniE3V2

//#define I2C_EEPROM  // use I2C EEPROM on SRK PRO v1.1 e.g AT24C256
//#define SKR14_PowerLossKit // Bigtreetech power loss kit for SKR14

//#define SKR_2209
//#define SKR_2130
#define SKR_UART // Configure SKR board with drivers in UART mode or SPI for TMC2130
//#define SKR_ReverseSteppers // Some users reported directions backwards than others on SKR with various drivers.
//#define DualZ // Uses 5th driver on CRX or SKR boards as Z2

//#define PowerShutoffKit
 /*
  *
  * If any non-stock dual extruder is used, define type here
  */

  //#define Dual_BowdenSplitterY
  //#define Dual_CyclopsSingleNozzle
  //#define Dual_ChimeraDualNozzle

//#define POWER_LOSS_RECOVERY //Large and does not fit with any other features on Melzi, or UBL on Atmega

//Add filtering to endstops when long extensions are used. Makes homing more reliable but less accurate.
//#define CableExtensionNoiseFilter

/*
   Choose a probe grid density below. Faster probes less points, but is less accurate.
   Extreme is for extremely uneven or tilted bed surfaces.
   UBL and Extreme are recommended with solid bed mounts as it becomes a one time commissioning.
   Standard is recommended in most other scenarios.
*/
//#define MeshFast
//#define MeshStd
//#define MeshFine
//#define MeshExtreme

/*
   Disables SD Sort, Autotemp, Arc support, Linear Advance (Unless overridden with OrigLA above), Big edit fonts, and a few other little things
   Intended to resolve issues with certain newer boards experiencing motion errors under load.
   Enables Slim Menus
*/
//#define LowMemoryBoard

/*
   Enclosure Controls
*/
//#define EnclosureLight // Uses 5vdc LED's hooked to D12
//#define EnclosureTempSensor // Uses PT100 Probe hooked to A12, only partially implemented upstream
//#define EnclosureHeater //Planned to use A11 to control heater upstream, and repurpose the unused y max as the fan output. Not yet fully implemented upstream

//#define UnstableTemps // define if temps are unstable and you need a temporary workaround

/**
 * Marlin 3D Printer Firmware
 * Copyright (c) 2020 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (c) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */
#pragma once

/**
 * Configuration.h
 *

**Comment by InsanityAutomation** [comment]
Please see the discord links in the branch ReadMe for custom compiling support. Many more people there can help much easier and faster than just waiting till I circle around to this queue.

3D Printing Discord - https://discord.gg/MZrsgVU
Marlin Discord - https://discord.gg/n5NJ59y
