### ISSUE TITLE
Solid Bed Mounts causes compiling failure

### ISSUE THREAD

**Issue by mezdezin** [InsanityAutomation/Marlin#177]
uncommenting the solidbedmounts line, it fails compiling.  see error below:

Arduino: 1.8.12 (Windows 10), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

sketch\src\lcd\extui\lib\Creality\Creality_DWIN.cpp: In function 'void ExtUI::onIdle()':

sketch\src\lcd\extui\lib\Creality\Creality_DWIN.cpp:183:28: error: 'LEVEL_CORNERS_HEIGHT' was not declared in this scope

         setAxisPosition_mm(LEVEL_CORNERS_HEIGHT, (axis_t)Z);

                            ^~~~~~~~~~~~~~~~~~~~

sketch\src\lcd\extui\lib\Creality\Creality_DWIN.cpp: In member function 'void ExtUI::RTSSHOW::RTS_HandleData()':

sketch\src\lcd\extui\lib\Creality\Creality_DWIN.cpp:760:29: error: 'LEVEL_CORNERS_INSET_LFRB' was not declared in this scope

   constexpr float lfrb[4] = LEVEL_CORNERS_INSET_LFRB;

                             ^~~~~~~~~~~~~~~~~~~~~~~~

sketch\src\lcd\extui\lib\Creality\Creality_DWIN.cpp:1243:30: error: 'LEVEL_CORNERS_Z_HOP' was not declared in this scope

           setAxisPosition_mm(LEVEL_CORNERS_Z_HOP, (axis_t)Z);

                              ^~~~~~~~~~~~~~~~~~~

sketch\src\lcd\extui\lib\Creality\Creality_DWIN.cpp:1251:30: error: 'LEVEL_CORNERS_Z_HOP' was not declared in this scope

           setAxisPosition_mm(LEVEL_CORNERS_Z_HOP, (axis_t)Z);

                              ^~~~~~~~~~~~~~~~~~~

sketch\src\lcd\extui\lib\Creality\Creality_DWIN.cpp:1259:30: error: 'LEVEL_CORNERS_Z_HOP' was not declared in this scope

           setAxisPosition_mm(LEVEL_CORNERS_Z_HOP, (axis_t)Z);

                              ^~~~~~~~~~~~~~~~~~~

sketch\src\lcd\extui\lib\Creality\Creality_DWIN.cpp:1267:30: error: 'LEVEL_CORNERS_Z_HOP' was not declared in this scope

           setAxisPosition_mm(LEVEL_CORNERS_Z_HOP, (axis_t)Z);

                              ^~~~~~~~~~~~~~~~~~~

sketch\src\lcd\extui\lib\Creality\Creality_DWIN.cpp:1275:30: error: 'LEVEL_CORNERS_Z_HOP' was not declared in this scope

           setAxisPosition_mm(LEVEL_CORNERS_Z_HOP, (axis_t)Z);

                              ^~~~~~~~~~~~~~~~~~~

exit status 1
Error compiling for board Arduino Mega or Mega 2560.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by InsanityAutomation** [comment]
This option only removes a menu to save a little program space. Its typically only recommended for use on the smaller Melzi boards. For the touchscreen machines, it is required to support the function in the touchscreen, so turning off the menu and its settings is not supported.
