### ISSUE TITLE
Probing ENDER 5 Plus

### ISSUE THREAD

**Issue by Docomar750** [InsanityAutomation/Marlin#184]
Hi

Just a question really how do i reduce the probing back to 16 from 25 on ender 5 plus using mesh stantard still using original touch screen.

**Comment by nitewing76** [comment]
It's in the configuration.h

**Comment by InsanityAutomation** [comment]
Its really recommended to probe a finer mesh and store it in EEPROM to recall rather than shrinking the mesh. Regardless, as stated above, configuration.h and adjust GRID_MAX_POINTS_X where it calls 5 back to 4.
