### ISSUE TITLE
cr10s pro v2 hemera z home issue

### ISSUE THREAD

**Issue by aurochsen** [InsanityAutomation/Marlin#185]
### Description

After a new hemera install on cr10s pro v2 the z home isn't correct. When the bltouch goes to measure the head crashes into the right gantry the second row it probes off the bed. I set the correct bltouch offset. 

configuration.h - https://pastebin.com/8DyarxMT
I made no changes to configuration.adv

**Comment by InsanityAutomation** [comment]
This can change drastically depending which mounting bracket you used. Do you have a link to the mounts that you installed?

**Comment by aurochsen** [comment]
Hi,
I used this bracket - https://www.thingiverse.com/thing:4141883 while following the teaching tech guide. I was able to adjust it after a lot of trial and error and settled on settings that seem to work well but lose build volume.

**Comment by KSPjohnFX** [comment]
I am having a similar issue but I suspect it to have a different cause. No matter the settings I use for BL-Touch offset or nozzle home offset the first probe is always in the same place off the print bed to the left and front. Depending on the settings, it reports different x and y coordinates yet always probes in the same place. As such, I cannot level my bed using my BL-Touch

**Comment by tmitch205** [comment]
That particular mount doesn't bring the stepper motor out far enough to miss the mounting screws for the belt pully on the right. That is probably ok for the MAX, but it is an issue for the 10S Pro V2... This is the plate that I use and it works really well. The file was sent to me from TinyMachines as the one that is similar on thingiverse  doesnt trip the x endstop. I added the BLTouch mount and fan duct that is compatible with this setup as well. 

[Hemera Base.zip](https://github.com/InsanityAutomation/Marlin/files/6728234/Hemera.Base.zip)

**Comment by aurochsen** [comment]
Excellent, I will try those instead hopefully reclaim my full size again. Thank you @tmitch205

**Comment by burnsy180** [comment]
> That particular mount doesn't bring the stepper motor out far enough to miss the mounting screws for the belt pully on the right. That is probably ok for the MAX, but it is an issue for the 10S Pro V2... This is the plate that I use and it works really well. The file was sent to me from TinyMachines as the one that is similar on thingiverse doesnt trip the x endstop. I added the BLTouch mount and fan duct that is compatible with this setup as well.
> 
> [Hemera Base.zip](https://github.com/InsanityAutomation/Marlin/files/6728234/Hemera.Base.zip)

I've just done this same install and found exactly the same problems. I notice the slot in this base for the x tensioner, but how doesn't this one miss the X stop? I had to grind away a portion of [this mount](https://www.myminifactory.com/object/3d-print-e3d-hemera-mount-for-cr-10s-pro-and-cr-10-max-106055) recommended by E3D so the X stop would touch the original metal mount.
