### ISSUE TITLE
Twin entries in platformio.ini on CrealityDWin_2.0 branch

### ISSUE THREAD

**Issue by Iveusse** [InsanityAutomation/Marlin#192]
### Description

platform.io cannot build due to twin entries in platformio.ini

### Steps to Reproduce

Pull last commit (93ecbfa)
Start a build (E5P_UBL_SIntH on my side)

**Expected behavior:** Build happens !

**Actual behavior:** Error as below:
Error: Invalid '...\GitHub\Ender5PlusMarlin\platformio.ini' (project configuration file): 'While reading from '...\\GitHub\\Ender5PlusMarlin\\platformio.ini' [line 1407]: section 'env:CRXPro_BIL_NoFil' already exists'

**Comment by Iveusse** [comment]
Lines 1407 to 1477 are duplicates

**Comment by InsanityAutomation** [comment]
Pulled the duplicated lines, thanks seems it botched the merge from the devel branch
