### ISSUE TITLE
Unable to compile MarlinCrealityDwin_2.0 on arduino ide 2:1.0.5+dfsg2-4.1

### ISSUE THREAD

**Issue by Tasmedic** [InsanityAutomation/Marlin#222]
I'm relatively new to Arduino programming but have adapted and uploaded Marlin Firmware for my CR-10S pro v2 previously with no problems. However your latest source won't compile, even when the defaults are left alone in your Marlin.ino files
Please help, and if it's an idiot mistake, I will be duly humbled, as well as grateful. 

Unable to compile MarlinCrealityDwin_2.0 on arduino ide 2:1.0.5+dfsg2-4.1

### Steps to Reproduce

1. Run arduino ide 2:1.0.5+dfsg2-4.1
2. Open Marlin.ino from your repository MarlinCrealityDwin_2.0
3. Run compile by clicking the "tick box" in the toolbar top of page

Note, the error occurs whether the Configuration.h and/or Configuration_adv.h files have been altered or not. 

**Expected behavior:** [What you expect to happen]
Should compile with no errors

**Actual behavior:** [What actually happens]
Fails to compile with the following error:

core.a(main.cpp.o): In function `main':
/usr/share/arduino/hardware/arduino/cores/arduino/main.cpp:5: undefined reference to `setup'
/usr/share/arduino/hardware/arduino/cores/arduino/main.cpp:15: undefined reference to `loop'
collect2: error: ld returned 1 exit status

Here's a screen capture

![screen](https://user-images.githubusercontent.com/89506790/130883362-04641cac-331c-4fd7-9403-61430679a591.jpg)

Thanks for your help

Chris

**Comment by InsanityAutomation** [comment]
Arduino IDE is no longer tested or supported, please use VSCode and PlatformIO.
