### ISSUE TITLE
Levelling DURATION (determining 16/25/36 points, doublesampling) needs to be configurable

### ISSUE THREAD

**Issue by mikishapiro** [InsanityAutomation/Marlin#224]
The latest HEX took sampling to 36 points, double-sampling each, heating bed for each. That's 72 bed heat tweaks. The precision is good, but it comes with a huge time tradeoff. 
This needs to be somehow configurable (via UI, via GCODE command) not hard-set in the firmware. And documented, unless it's already possible to do so.

For two reasons:
1. Time tradeoff.
2. If my UI firmware is of a version that displays 25 points, maybe I prefer to sample 25 times just so the UI is meaningful and I can make sense of the data shown.

Please make this a configurable and document how to configure it :)

**Comment by InsanityAutomation** [comment]
There is no provision in Marlin for this to be runtime configurable. Most boards we are using don't have nearly enough ram to even consider it.
