### ISSUE TITLE
Ender 6 blobs on round corners

### ISSUE THREAD

**Issue by subhead** [InsanityAutomation/Marlin#229]
I have noticed that with this firmware (https://github.com/InsanityAutomation/Marlin/blob/CrealityDwin_2.0/Hex%20Files/firmware_Ender6_BLT_DW7.4.bin.zip) i have blobs on round corners. Lowering the slicer resolution helps a bit, but the print quality gets really bad. I also tested the bleeding branch firmware (https://github.com/InsanityAutomation/Marlin/blob/CrealityDwin2.0_Bleeding/Hex%20Files/firmware_Ender6_BLT_DW7.4.bin.zip) but ran into the same problem with round corners. Is there anything i can do? I would really like to use this firmware on my ender 6 because the creality firmware is horrible.

What i also noticed with this firmware i can not connect with 115200 baud anymore. I need to set the baud rate to 250000. Could that maybe lead into that kind of problems?

thanks for any help.

![photo_2021-10-10_17-09-45](https://user-images.githubusercontent.com/601434/136930046-ca71f578-3f1c-4024-9ba3-aa93ae586f27.jpg)

**Comment by Bhumpe** [comment]
If you using Cura, try with the following settings under "Mesh Fixes"
Maximum Resolution -> 0.7
Maximun Travel Resolution -> 0.7
Maximum Deviation -> 0.075
These changes have helped me with similar blobs.

**Comment by subhead** [comment]
Thanks for you reply! I normaly use PrusaSlicer is there something in PrusaSlicer besides the resolution settings i can tweak to get rid of these blobs? If i need to switch back to Cura, i will stick with the default firmware from creality. I really dont like Cura.

**Comment by Bhumpe** [comment]
I have been messing around with Super Slicer this weekend, based on same slicer as Prusa, but I was no able to tweak the settings to get rid of this blobs.
I tried among other settings, different values in the resolution setting, nothing worked.
On Cura it works perfectly at 150mm/s with modified bowden setup and BTT hotend with this resolution setting. but for Prusa Slicer I have no solution today.
Let me know if you find a solution for this issue. I also prefer Prusa/super Slicers UI and tweeks more than Cura.
One Question, Why do you stick with Creality FW when using Cura? Insanity Machine works perfectly also with cura,

**Comment by subhead** [comment]
First of all thanks for your help!

I stick with the Creality FW because i want to use PrusaSlicer. With the FW von Insanity Maschine i have these blobs/zits. Or is there another FW from Insanity Maschine for the Ender 6 that works with PrusaSlicer that i missed?

**Comment by Bhumpe** [comment]
Ahh, I have not tried the Creality FW at all, never thought the FW could be a root cause of this issue. This I need to look into. I completely my own settings from the Insanity Machine releases, however I'm not an expert at all..

**Comment by subhead** [comment]
Would you mind sharing your configuration files for the ender 6?

**Comment by Bhumpe** [comment]
Sure, This is my Cure Profile for the Ender6, Please notice, it's optimised for 150mm/s which is dialed in on mine
[0.2 Ender6.curaprofile.zip](https://github.com/InsanityAutomation/Marlin/files/7408803/0.2.Ender6.curaprofile.zip)

**Comment by subhead** [comment]
Thanks i will give your config a shot.

**Comment by subhead** [comment]
Today i saw that there is a 7.4.3 release and i tried that on one of my ender 6. I was really surprised with the results. With this Version the blobs are completly gone. I can slice anything with prusaslicer and the print looks great. I dont know what has changed, but thanks for that. :-)

But i have one last question. Is there a way to obtain the configuration files that where used to build this version? 

Thanks!

**Comment by InsanityAutomation** [comment]
The release tags show the repo at the state the binaries were built - https://github.com/InsanityAutomation/Marlin/releases/tag/DW743
