### ISSUE TITLE
Where did the screen files go?

### ISSUE THREAD

**Issue by napter** [InsanityAutomation/Marlin#230]
I'm trying to figure out how to update the screen firmware on an Ender 5 Plus after updating the board. My searches lead me to a few links like https://github.com/InsanityAutomation/Marlin/blob/CrealityDwin2.0_Bleeding/CR-XABL_Screens_V2Rev2.7z to get the binaries for the screen but it 404's now.

Where can I find the latest files to update the screen firmware? Do the binaries still exist? If not, how can I compile them?

Thank you

**Comment by InsanityAutomation** [comment]
CRX features were merged into a single combined screen set
https://github.com/InsanityAutomation/Marlin/blob/CrealityDwin_2.0/TM3D_DWINCombinedScreens_V6.7z
