### ISSUE TITLE
TM3D_DWINCombinedScreens_V6.7z  sound problem

### ISSUE THREAD

**Issue by Morgan-T-fr** [InsanityAutomation/Marlin#238]
### Description

strange sounds on CR10S PRO VE with TM3D_DWINCombinedScreens_V6.7z and 10SProV2_BIL_DW7.4.4.hex firmware

### Steps to Reproduce

1. install firmware
2. install screen binary
3. reset settings and restart

**Expected behavior:** 

known sound (as find in .wav files

**Actual behavior:** 

unknown sounds

**Comment by rebelonion** [comment]
I am also having this same problem on CR-10S PRO V1 with TM3D_DWINCombinedScreens_V6.7z and 10SPro_BIL_DW7.4.4.hex firmware.

**Comment by phehr2** [comment]
I am also having this same problem on CR-10S PRO V1 with TM3D_DWINCombinedScreens_V6.7z and 10SPro_BIL_DW7.4.4.hex firmware.
