### ISSUE TITLE
Enhancement Request - M117 Messages to LCD

### ISSUE THREAD

**Issue by mwolter805** [InsanityAutomation/Marlin#24]
Hello,
Again, thank you for your work on this project! Requesting M117 messages be passed to the LCD. It would be helpful if M117 messages passed in (from OctoPrint for example) are able to be displayed on the LCD screen. There is quite a bit of helpful info that can be presented, such as the OctoPrint IP address, remaining print time, etc.

**Comment by mwolter805** [comment]
silent_ninja1 answered this question on Reddit.

Unfortunately not as there is no always present data field to write it to... Nothing that takes a string either. Just numerical status values.

**Comment by InsanityAutomation** [comment]
As a side note, thats me on Reddit as well :)

**Comment by InsanityAutomation** [comment]
Closing as this just isnt possible with the creality screen files, as disappointing as that is.
