### ISSUE TITLE
Ender 6 Z Axis turns in wrong direction

### ISSUE THREAD

**Issue by phantom101** [InsanityAutomation/Marlin#250]
Hello,
First THANK YOU for making a better Firmware !

I want to update my Ender 6 but get a strange behaviour after the update the Z Axis turns in wrong direction ...
If i press up it turns the bed down.
Sadly also in printing when the bed should move down it move up.

Moving home is working here the Printer turns the bed up.

Before it worked without any problems ...

Next sad news after flashing back to the original Firmeware the problem is the same :-(

Please help.

Thank you !!!

**Comment by InsanityAutomation** [comment]
There was debate early on with the arrow direction. Most CNC operators expect the up arrow to move the axis position up, therefore bed moves down. However most users here are hobbyists who don't have the prior expectation and expect the physical movement to match.

Basically no matter which one we choose, a set of users will say it's backwards. The directions it moves now keep the code and buttons common between all dgus display machines though, and isn't considered a bug.
