### ISSUE TITLE
firmware_Ender7_BLT_ZM_DW7.4.4 Linear Advance 

### ISSUE THREAD

**Issue by Gini9** [InsanityAutomation/Marlin#252]
Hey
I tried to set Linear Advance with the firmware_Ender7_BLT_ZM_DW7.4.4.
But this doesn't work. I enter m900 in the console and get the error "unknown command".

**Comment by InsanityAutomation** [comment]
Linear advance is currently not enabled for the machine in the default builds. A custom file could be compiled for it, however we dont often enable this by default due to the issues it causes locking up TMC drivers.
