### ISSUE TITLE
Support for Ender 6 on 4.2.7 Board

### ISSUE THREAD

**Issue by mtregard** [InsanityAutomation/Marlin#256]
### Description

The Ender-6 comes with 4.3.1 Boards that have cheap stepper-drivers for Z and E. Especially the E is driving me crazy when printing with retractions. I tried with a 4.2.7 Board that has all 2225 drivers, but stock firmware and also yours will not move the steppers. Same board with Ender 3 V2 firmware moves all steppers, but naturally config is all wrong.  

CAN YOU PLS MAKE A BUILD FOR THIS SETUP? Or at least give me some hints as to what I would need to change to compile it myself?!!!

**Comment by mtregard** [comment]
For all of you looking for a solution. Build yourself using Platform.io.

1. in **configuration.h** change 

```
  #elif ENABLED(MachineEnder6)
    #define MOTHERBOARD BOARD_CREALITY_V431
```

to

```
  #elif ENABLED(MachineEnder6)
    #define MOTHERBOARD BOARD_CREALITY_V427
```

2. Build Ender 6 Image to your liking
3. **_IMPORTANT:_** swap X&Y Stepper cables on the board (it seems Ender 6 is COREYX not XY ;)). I believe this could be changed with config as well, but this is my first look into Marlin source-code so I skipped that for now.

**Comment by mtregard** [comment]
So it should be fairly easy to add a build-config for this very much desirable scenario...

**Comment by InsanityAutomation** [comment]
Just to be sure I understand the reasoning behind the board change, is this driven by cost / availability of replacements? Not difficult to add at all as a predefined configuration though.

**Comment by mtregard** [comment]
Thanks for getting back to me. It's purely a matter of noise from the stepper-drivers for Z and E. I believe not all 4.3.1-boards are affected by this, but I also know that I'm not alone. I tried 3 such boards from different sources and they all had cheap drivers on them. When printing with lots of retractions it's a real pain.

**Comment by houseofbugs** [comment]
The 4.2.7 is not a direct replacement for the 4.3.1. If you are swapping to the 4.2.7 then you should have the knowledge to do so, including firmware changes. This is not an issue, but a user problem so it should not be present in the Github issue queue.

**Comment by mtregard** [comment]
@houseofbugs : I agree that this is not at all an issue, but I did not know any other means of getting attention. Not everyone who can swap a board is capable of doing firmware changes. The Ender 6 with a BIQU H2 and some other mods CAN be a very capable and silent machine at a more than acceptable price point. Would be nice if others could simple download your excellent firmware and continue printing....

**Comment by houseofbugs** [comment]
> @houseofbugs : I agree that this is not at all an issue, but I did not know any other means of getting attention. Not everyone who can swap a board is capable of doing firmware changes. The Ender 6 with a BIQU H2 and some other mods CAN be a very capable and silent machine at a more than acceptable price point. Would be nice if others could simple download your excellent firmware and continue printing....

That is not @InsanityAutomation problem if you're too lazy to make a non standard board work with a specific machine via firmware code changes.

The issue queues on GitHub are not for your own personal tech support. Stop doing it.

**Comment by mtregard** [comment]
@houseofbugs: It's not about me; I have made the changes and built the image. It's about making this accessible to others.  But whatever you say is probably correct. You seem just like the type ;)

@InsanityAutomation: I think it would be great to have a dedicated build-config for this setup (you already have an existing build-modifier for silent boards which might be usable) but I understand that not every variant can be supported and I also do not know how popular this setup would actually be. On the other hand it wouldn't make any sense to fork the project for just a couple of config changes.
