### ISSUE TITLE
PID calibration returns immediately "PID Tune Finished" texton Ender5 Plus

### ISSUE THREAD

**Issue by traysh** [InsanityAutomation/Marlin#270]
### Description
Running PID calibration *on a fresh boot* using the touch screen on Ender 5 Plus (silent board) returns immediately with the message "PID Tune Finished", even tough the PID Autotune is running on background (I can see its messages in the serial console).  

On the other hand, if I first run PID autotune using the serial console and afterwards try it using the touch screen, it works as it should.

### Steps to Reproduce

1. Flash latest hex E5P_UBL_Slnt_DW7.4.6.hex.zip
2. Turn Machinhe on
3. Run PID Autotune using the touch screen

**Expected behavior:** There should be visual feedback that the PID autotune is running

**Actual behavior:** The visual feedback is misleading, telling the PID autotune finished

#### Additional Information

Using the pre-compile hex E5P_UBL_Slnt_DW7.4.6.hex.zip from origin/CrealityDwin_2.0 branch

**Comment by InsanityAutomation** [comment]
This was an upstream bug caused by changes in the PID code that got the event handler out of order. The message was fired but the PID tune continued in the background with the screen left in an odd state as not all commands could be processed while tuning was still active.
