### ISSUE TITLE
CR 10 (notso) SMART

### ISSUE THREAD

**Issue by blancharke** [InsanityAutomation/Marlin#272]
Trying to install firmware_CR10Smart_DW7.4.6 but printer doesn't turn on. 
Screen firmware went ok.
I have the CR-FDM-V2.5.S1_100 motherboard.  
Can't find if this firmware is compatible with this main board.

Anyone can clarify?

**Comment by blancharke** [comment]
Just saw this in configuration.h 

#elif ENABLED(MachineCR10SmartPro)
    #define MOTHERBOARD BOARD_CREALITY_V25S1
  #elif ANY(MachineCR6, MachineCR6Max, MachineCR10Smart)
    #define MOTHERBOARD BOARD_CREALITY_V453

The non pro is being shipped with one of the 2 boards, mine seems to have the pro motherboard in it.

Can i just change the line for the actual motherboard? or do I have to change other things to?

**Comment by InsanityAutomation** [comment]
Can use the same settings, but build with the environment for the Pro bootloader. Next release will have prebuilt options for both bootloaders.
