### ISSUE TITLE
cr 10 smart pro stops extruding randomly during print

### ISSUE THREAD

**Issue by EXCISIONMODZ** [InsanityAutomation/Marlin#279]
https://youtube.com/shorts/x2Bbw6p1m2k?feature=share

im using the bin file you linked me on discord

**Comment by Storpell** [comment]
I have the same issue

**Comment by InsanityAutomation** [comment]
Found a build made it out at one point with Linear Advance enabled before the fix that allowed it to work with standalone 2208 drivers.
