### ISSUE TITLE
CR-10S Pro V2 / DDX / Slow First layer

### ISSUE THREAD

**Issue by tmitch205** [InsanityAutomation/Marlin#284]
### Description

CR-10S Pro V2 with DDX and Copperhead hotend. I have 2 of these printers and they are identical. Upgraded the screen files and firmware on the first Printer using an SD card for the screen and Arduino for the firmware. Changed nothing at all, just used the SD card on the second screen and uploaded the firmware onto the second printer. First printer prints without issues. The second printer has issues printing the first layer. It acts like it is waiting 5 to 15 seconds at the end of one line of code, before reading the next line. 2nd layer and beyond seem to print normally. I have resliced the files, same result. I have moved the SD card without changing the file over to the first printer, it prints without issue. If I downgrade the second printer back to 7.4.4, I get a little pause between layers, but this issue is not present 

(Update,I can print normally from directly from the laptop through S3D, but I had to increase the baud rate to 250,000 to even communicate with the printer. In the past, it's always been 115,200.)

### Steps to Reproduce

1. Slice the file
2. Put the file on the card and place the card in the printer
3. Start file.

**Expected behavior:** [Go from each line of code seemlessly]

**Actual behavior:** [paused for 5 to 15 seconds between lines of code]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.
[Config Files.zip](https://github.com/InsanityAutomation/Marlin/files/9847998/Config.Files.zip)

**Comment by InsanityAutomation** [comment]
This is an upstream issue with the card reader. Code was refactored awhile back and is less robust (but smaller)
