### ISSUE TITLE
Z steps limit in firmware_E3_Touch_BLT_ZM_DW7.4.6

### ISSUE THREAD

**Issue by keegi1** [InsanityAutomation/Marlin#286]
I changed 8mm pitch leadscrew to 2mm pitch leadscrew on Z axis of my Ender 3 and needed to change Z steps from 400 to 1600, but maximum steps on that firmware seems to be 999.9 Why it's limited and how can I change that?
Edit:
I recompiled firmware with Z1600 and got it working, but touchscreen shows now 600 instead of 1600. So the bug is in the touchscreens firmware.

**Comment by InsanityAutomation** [comment]
That value overflows the data type limit for the field. It wont be changed in this project unless there is a supported machine requiring it.
