### ISSUE TITLE
[INFO] Compatible with CR10 Smart Pro?

### ISSUE THREAD

**Issue by boromyr** [InsanityAutomation/Marlin#294]
I wanted to know if this "CrealityDwin2.0_Bleeding" firmware would be compatible with CR10 Smart Pro, both horizontal screen version and vertical screen version, with the UI of CR6, thanks.

Any response or opinion releases you from any liability for any damage or malfunction.

**Comment by InsanityAutomation** [comment]
We never take any liability for any issue installing aftermarket firmware, as Creality especially makes many changes to a machine during its product cycle, not all of them compatible with the same firmware. While yes, it works just fine on my machine, we make no guarantee it will work as well on yours.
