### ISSUE TITLE
Z_MIN_POS is incorrect for T_REX3 Upgraded

### ISSUE THREAD

**Issue by jim-edwards** [InsanityAutomation/Marlin#30]
### Description

Z_MIN_POS is set to 3 for ENABLED(TREX3_UPGRADE).  It should be set to 0.  Looks like a typo/translation error from my previous pull request just FYI.

### Steps to Reproduce

1. Attempt to print with TREX3_UPGRADE.
2. Observe that nozzle won't get closer to the bed, should allow Z=0

**Expected behavior:** Set Z_MIN_POS = 0

**Actual behavior:** Z_MIN_POS observed = 3

**Comment by InsanityAutomation** [comment]
Fixed this one a couple days ago - typo.
