### ISSUE TITLE
Unable to edit X offset of T-Rex 3

### ISSUE THREAD

**Issue by jim-edwards** [InsanityAutomation/Marlin#31]
### Description

On the T-Rex 3 IDEX printer, modifying the X head offset doesn't work from the UI.  Setting it manually from G-Code commands works OK.  It always tries to set it to the same value, regardless of how to twist the control nob.

### Steps to Reproduce

1. Load firmware, reset to defaults.
2. In the UI, go to Configuration and try and change the X offset.
3. Current value displayed is the firmware default: 441.36 for example.
4. Twist the nob to change the value, it goes to 361 and you can't change it from there.

**Expected behavior:** 

Allow the value to be changed to fine-tune your specific printers offsets.

**Actual behavior:** 

Can't change the value, it just sets it to 361 and doesn't allow it to change.

#### Additional Information

Using the stock config, either TREX3 or the TREX3_UPGRADE set.

**Comment by InsanityAutomation** [comment]
Fyi this was fixed upstream I'll update these branches tonight.
