### ISSUE TITLE
LIN_ADVANCE disabled for CR-10S PRO?

### ISSUE THREAD

**Issue by chunter1** [InsanityAutomation/Marlin#40]
Is there a reason why LIN_ADVANCE is disabled for the CR-10S PRO?

**Comment by InsanityAutomation** [comment]
TMC2208 drivers go into shutdown with linear advance when in spreadcycle mode. It can work with high step/mm counts (eg with a bondtech or titan extruder) but results vary. Without uart to set them to spreadcycle its highly likely to cause issues.

**Comment by chunter1** [comment]
Ok, thank you for the info.
Nothing for the CR-10S PRO then.
