### ISSUE TITLE
Change Microstepping?

### ISSUE THREAD

**Issue by SirRenix** [InsanityAutomation/Marlin#42]
Hi, Im new in Marlin and I have question about the Microstepping settings?
It is possible to change in example 1/16 to 1/32? And why is the option tmc2208 disabled in configuration.adv.h?
I have change the gear on the X Axis to a 36Teeth GT2 and I will that the resolution is the same before, because of a modification on the frame with linear rails for the belt, otherwise I have problems.
Thank You

**Comment by InsanityAutomation** [comment]
Microstepping on these is not possible to change as we do not have the hardware to do so. The embedded drivers do not have i2c lines for digipots, the manufacturer did not provide the UART pins and they did not provide any jumpers to select these. The only way to adjust movement is with steps/mm adjustment, which can be done via gcode with M92.
