### ISSUE TITLE
Creality_Marlin2.0.x - Error compiling

### ISSUE THREAD

**Issue by camprevail** [InsanityAutomation/Marlin#43]
Error: `sketch\src\HAL\HAL_AVR\u8g_com_HAL_AVR_sw_spi.cpp:65:20: fatal error: U8glib.h: No such file or directory`

Trying to compile for CRX with Mega2560

**Comment by InsanityAutomation** [comment]
Its looking for the U8Glib library to be installed. Under the Arduino IDE you need to add it from the library manager.
