### ISSUE TITLE
CR-10S PRO is ABL really working?

### ISSUE THREAD

**Issue by chunter1** [InsanityAutomation/Marlin#44]
Is the ABL of the CR-10S PRO running latest "Creality_DWINTest" firmware really working correctly?
Here is what i did to calibrate and what is the result when printing a 0.1mm test pattern:

1. Erased the eeprom with M502 M500
2. Leveled both Z-axis steppers
3. Heated bed to 50°C
4. Did the manual (aux) leveling using the 4 bed screws
5. Turned off ABL on the Screen
6. Started the ABL measurement
7. Turned on ABL on the screen
8. Printed the test-pattern and got shocked :)

Are the ABL correction values from the terminal output (M501) somehow ok with the ones shown on the LCD (see attachments).
What am i doing wrong here?

![LCD_correction_values_and_test_print](https://user-images.githubusercontent.com/16907942/59461710-48a02d80-8e22-11e9-89e8-31a99d24a755.jpg)
![M501_output_in_terminal](https://user-images.githubusercontent.com/16907942/59461717-4a69f100-8e22-11e9-867f-a52871feb457.jpg)

**Comment by juliandroid** [comment]
I have some distant memory that might be incorrect:
1. those settings are not stored in eeprom currently;
2. values were populated in wrong order (for example shifted or rotated at 90 degrees)

btw, try the Bed Visualiser (OctoPrint) which have optoins to rotate columns/rows, to match your data with visualization

**Comment by wpte** [comment]
Does that mean it's required to do ABL before every print instead of retrieving the values?

**Comment by juliandroid** [comment]
I don't know, I don't use DWINTest branch. What I saw there is that all writtings to eeprom are commented out, so for example auto bed leveling icon in the LCD menu is lost on power down.

Take a look also at this ticket: https://github.com/InsanityAutomation/Marlin/issues/22

**Comment by wpte** [comment]
> I don't know, I don't use DWINTest branch. What I saw there is that all writtings to eeprom are commented out, so for example auto bed leveling icon in the LCD menu is lost on power down.
> 
> Take a look at this ticket: #22

Okay, what's the recommended "stable" branch then?

**Comment by juliandroid** [comment]
From the product page https://www.tinymachines3d.com/pages/10spro it leads to Creality_DWINTest branch :)

Personally I still stay on "official" Creality firmware until Marlin 2.x become relatively stable :)

**Comment by InsanityAutomation** [comment]
Whats on the screen is skewed after a restart, one of the things 2.0 will fix. Did the test pattern include M420 S1 after G28 in the start script?

**Comment by chunter1** [comment]
Yes, it's included in my simplify3d start script:

```
...
G28 X0 Y0 Z0 ; home X/Y/Z axes
M420 S1 ; use existing ABL data from eeprom
...
```

**Comment by InsanityAutomation** [comment]
One of the issues with Bilinear is that its not as simple to adjust individual probe points. 2.0 will have UBL functioning. I did verify that its indeed working as accurately as the probe reads with an intentional tilt of 2mm.
