### ISSUE TITLE
CR-10S PRO softer homing bumps similar to original Creality fw

### ISSUE THREAD

**Issue by chunter1** [InsanityAutomation/Marlin#46]
Compared to the original Creality firmware, the homing bumps on the X and Y axis are rather hard.
The original firmware seems to do a "soft rebounce" when hiting the switches.
Is there a setting in the firmware that can be adjusted?

**Comment by InsanityAutomation** [comment]
Ive increased the #define HOMING_BUMP_DIVISOR from 2 to 3 for B7
