### ISSUE TITLE
Missing CR-X hex files

### ISSUE THREAD

**Issue by LMS0815** [InsanityAutomation/Marlin#48]
### Description

Missing CR-X files

### Steps to Reproduce

Please provide the 
CR-X_1.1.9_xx.hex and
CRX_BLTouch_ProScreens_1.1.9_xx.hex

files.

**Comment by PaulF8080** [comment]
Build scripts normally build things like hex file only when t's dependencies change. The CRX directories didn't change so the hex files should be good.

**Comment by InsanityAutomation** [comment]
Ive been tweaking some CRX things over the past week. Ill probably make new hex files for that along with support for the Max soon. All the recent changes have to do with leveling for the most part so not really applicable to a stock CR-X

**Comment by LMS0815** [comment]
Thank you @InsanityAutomation. I am using the 3D Touch already. ABL tweaking is exactly what I am looking for.
Current version (CRX_BLTouch_ProScreens_1.1.9_B5.hex)  has issues with OctoPrint receiving errors.

**Comment by LMS0815** [comment]
Is there any chance to set the  ABL probe offset via GCode (seems to be firmware hard coded)? 
Unfortunately, I do not know how to create a hex file on my own.

@InsanityAutomation
I like to adjust the probe offset according to this holder...
https://www.thingiverse.com/thing:3390657

Of cause I would be happy if you can share your BT/3D-Touch mount.

**Comment by LMS0815** [comment]
> Ive been tweaking some CRX things over the past week. Ill probably make new hex files for that along with support for the Max soon. All the recent changes have to do with leveling for the most part so not really applicable to a stock CR-X

Sorry to bother you... Any progress to share for CR-X?

**Comment by InsanityAutomation** [comment]
The 2.0 builds are mostly working, which is a vast improvement for the CRX. Ill be working on it some more this weekend. 2.0 completely automates the tool change process, no more slicer scripts needed, even for a purge bucket.

**Comment by LMS0815** [comment]
> The 2.0 builds are mostly working, which is a vast improvement for the CRX. Ill be working on it some more this weekend. 2.0 completely automates the tool change process, no more slicer scripts needed, even for a purge bucket.

Wow. I probably should print a  [_purge bucket_](https://www.thingiverse.com/thing:3485963) now . I am looking forward to flash my CR-X to 2.x and hope you can share is soon.

**Comment by InsanityAutomation** [comment]
FYI, 2.0 builds are posted, HEX files for CR-X included. Im closing this as resolved :)

**Comment by LMS0815** [comment]
> FYI, 2.0 builds are posted, HEX files for CR-X included. Im closing this as resolved :)

THANK YOU. Kindly share the link (I probably search the wrong folder)

**Comment by InsanityAutomation** [comment]
> 
> 
> > FYI, 2.0 builds are posted, HEX files for CR-X included. Im closing this as resolved :)
> 
> THANK YOU. Kindly share the link (I probably search the wrong folder)

Heres the updated branch - https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin_2.0

**Comment by LMS0815** [comment]
Thank you. Please send me the link.

24. August 2019 17:07, "InsanityAutomation" <notifications@github.com (mailto:notifications@github.com?to=%22InsanityAutomation%22%20<notifications@github.com>)> schrieb:
	FYI, 2.0 builds are posted, HEX files for CR-X included. Im closing this as resolved :)
