### ISSUE TITLE
CR-10S Pro bed size and ABL mesh

### ISSUE THREAD

**Issue by darknode** [InsanityAutomation/Marlin#49]
Why the bed size values in the firmware are different from physical size of the bed? It looks like nozzle could move outside of the bed by X-axis because of that.
```
#if (ENABLED(MachineCR10Std))
#define X_BED_SIZE 315
#define Y_BED_SIZE 310
#define Z_MAX_POS 400
#endif
```

Do 5x5 ABL mesh logic has some corrections to calculate correct positions on the bed? (I mean equal offsets by X on the left for 1 point and on the right for 5th point)

**Comment by InsanityAutomation** [comment]
Nozzle moves outside of the bed. Probe does not. Firmware knows the difference in distance from the probe to the nozzle.

**Comment by darknode** [comment]
I'm just trying to distribute ABL points more evenly across the bed, that's why I'm asking about X Max of 315 and not 310.

![Untitled Diagram (1)](https://user-images.githubusercontent.com/809429/60618372-ab139a80-9dde-11e9-86e6-ca6372cb9d08.jpg)

Gray circles are current ABL points, greens are what I'm trying to achieve, so cloud you please help me to understand why 315 :)

**Comment by ostehovelen** [comment]
> Nozzle moves outside of the bed. Probe does not. Firmware knows the difference in distance from the probe to the nozzle.

I'm using the CR-x and this mounting for probe https://www.thingiverse.com/thing:3438291, my probe goes outside the bed, how can i correct this, and where? :O

**Comment by ostehovelen** [comment]
I've tried the probe offset, it doesnt seem to do anything....?

**Comment by zyxep** [comment]
> Nozzle moves outside of the bed. Probe does not. Firmware knows the difference in distance from the probe to the nozzle.

I'm curious why write the bed as 310x315x400 when it's actually is 300x300x400 ?
I get it with the probe but still

**Comment by InsanityAutomation** [comment]
I just put a tape measure across mine, and X measures 310mm, where Y measures 320mm. Nozzle itself when Y is at the limit isnt quite off the bed, so physically the slightly larger dimensions match up. The probe points go as wide as the X gantry can reach. It cant go farther right without crashing. IIRC we left a couple mm buffer to account for manufacturing tolerances. The points are spread out as much as they can be to encompass the largest possible area.

**Comment by InsanityAutomation** [comment]
With UBL in there is even more differences people will notice, but for now im closing this. More work will be put into denser meshes in the future.
