### ISSUE TITLE
Clone Bltouch issue (3D Touch , brand Triangle)

### ISSUE THREAD

**Issue by Ahmadino** [InsanityAutomation/Marlin#50]
Dear Tinymachine 
I have a clone Bltouch (Triangle brand 3d touch) , all old frimwares   (B5 build v5 and before) before 26 February 2019 , works very well with BLtouch.
When you have add Bltouch v3 in the code in the build v6 and build v7, now it not working very well , i have put a jumper as you have mentioned , but still the problem exist, the nozzle crash the table .
This is a link for the issue :
[https://youtu.be/95j5j3EyHeo
(https://youtu.be/95j5j3EyHeo) 

I also increase and decrease the delay of Bltouch , and i uncomment #define BLTOUCH_FORCE_5V_MODE, without any success.
How can you help me please ?

**Comment by InsanityAutomation** [comment]
We dont put effort into testing and setting up for clones of patented products. For a clone they get confused by the new V3.0 commands, 

Marlin Main.cpp lines 2142-2146 comment out

#if ENABLED(BLTOUCH_FORCE_5V_MODE)
bltouch_command(BLTOUCH_5V_MODE);
#else
bltouch_command(BLTOUCH_OD_MODE);
#endif


Then also 2162 - 2169


#if ENABLED(BLTOUCH_FORCE_5V_MODE)
bltouch_command(BLTOUCH_5V_MODE);
#else
bltouch_command(BLTOUCH_OD_MODE);
#endif
if(deploy)
bltouch_command(BLTOUCH_SW_MODE);
