### ISSUE TITLE
CRX BLTouch DualRunout HowTo?

### ISSUE THREAD

**Issue by LMS0815** [InsanityAutomation/Marlin#53]
Thank you for sharing all your work and _sorry for raising an issue_, although I only have a question.
Is there any site, board, etc. where I can find the requirements of the  Dual Runout sensor (switch) and the pins they are connected to?  
The CR-X has a Creality Mega 2560 Board:
![Creality Mega 2560 Board Connections CR-X V22](https://user-images.githubusercontent.com/8235214/63754761-b4d4ee00-c8b5-11e9-82df-af91e1054e9a.jpg)
I am using the makebot Endstop v1.2:
![makerbot_endstop](https://user-images.githubusercontent.com/8235214/63783229-eae19480-c8ec-11e9-9a3f-805cbf76f85f.png)

**Comment by InsanityAutomation** [comment]
They are setup to use the X+ and Y+ endstop ports. Disabling the Lerdge option changes polarity if you find it reversed from what you have.

**Comment by LMS0815** [comment]
I tried the ports you advised. I probably need to disable the the _Lerdge option._ 
What is it? How to do it? I am not able to create a Hex on my own.
Any Gcode to do so?
Any terminal command?
Or should I just switch the cables...

**Comment by InsanityAutomation** [comment]
Missed the added question here... Switching the cables is the best route if you are not setup to compile. Ill be posting some guides on compiling from scratch soon though.

**Comment by LMS0815** [comment]
> Ill be posting some guides on compiling from scratch soon though.

Thank you. Looking forward to it.
