### ISSUE TITLE
M73 not working (CR-X)

### ISSUE THREAD

**Issue by LMS0815** [InsanityAutomation/Marlin#54]
After updating to CRX_BLTouch_DualRunout_2.0_B1.hex

Octoprint _M73-Progress-Plugin (0.1.0)_ is not working any longer.
Sending the command via Terminal (e.g. M73 P25) has no effect (No update to the LCD).

**Comment by InsanityAutomation** [comment]
Fixed in source yesterday. Ill be making new hex files Saturday with a few small tweaks.

**Comment by InsanityAutomation** [comment]
New hex files going up now
