### ISSUE TITLE
gcode M300 not working

### ISSUE THREAD

**Issue by LMS0815** [InsanityAutomation/Marlin#56]
[gCode M300](http://marlinfw.org/docs/gcode/M300.html) is not playing anything.

This should play a tune after print is ready
```
M300 S440 P200
M300 S660 P250
M300 S880 P300
```

**Comment by InsanityAutomation** [comment]
Im looking at fixing this gcode reliance on a physical pin defined for the beeper. Itll come around soon.

**Comment by InsanityAutomation** [comment]
Working in the current source, next hex will have it play the startup tune on M300
