### ISSUE TITLE
OctoPrint job never ends

### ISSUE THREAD

**Issue by LMS0815** [InsanityAutomation/Marlin#57]
After an OctoPrint print job is finished (NOT SD CARD) then Printer display keeps on claiming PRINTING.
I need to abort the job at the printer display to get control back, although OctoPrint is not printing any longer. And status is 100%

The same configuration had no issues with the Marlin 1.x. Therefor I assume this is a bug.

**Comment by SkullKill** [comment]
using the CrealityDwin_2.0 branch

on octoprint, it says 100%, printer physically is all good, (bed and hotend off,).

LCD Still shows 99%, with the stop, pause, adjust buttons. but on top of lcd, it says "TM3D 10S  Pro Ready" "Cool..."

as per attached picture

![IMG_20190902_084831](https://user-images.githubusercontent.com/20982257/64086927-68822600-cd6d-11e9-8ad8-6e5b7c510ad1.jpg)



p.s sending another print job from octiprint in this state works fine. 

============================================

============================================
FYI, when pressing the "Stop"
i get a message on octoprint, saying "Message from your printer" "UI Abort" with NO close or acknowledgement button! the message cannot be discarded. only thing that works is ESC button, even then it comes back after a reload of the page.



https://github.com/foosel/OctoPrint/issues/3171

according to @foosel from octoprint
> The prompt is _completely_ defined by the firmware according to the protocol. So if the firmware doesn't define a button, there won't be a button. 

![UI-Abort](https://user-images.githubusercontent.com/20982257/64087204-a16eca80-cd6e-11e9-9791-f1feba411ca6.jpg)

fyi, the UI Abort message is from

Marlin/src/lcd/ultralcd.cpp:      host_prompt_open(PROMPT_INFO, PSTR("UI Abort"));

all above issues are not there in the Creality_DWINTest branch

**Comment by LMS0815** [comment]
The octoprint _persistent_ message is a well known cache issue which is will beaddressed in Octoprint [V1.3.12](https://www.youtube.com/watch?v=NwUrvTi9TVc) 
Never the less the CrealityDwin_2.0 branch (CRX_BLTouch_DualRunout_2.0_B1.hex) has an issue not _knowing_, when octoprint finalized a job which is new. V 1.x did not have this issue with Octoprint  V1.3.11. The printer keeps waiting for data and is showing the printing display/status.

**Comment by InsanityAutomation** [comment]
Print job timer callback issues fixed upstream and new hex files going up today.
