### ISSUE TITLE
BL Touch 3.1 doesn't work?

### ISSUE THREAD

**Issue by Maalow** [InsanityAutomation/Marlin#59]
BL-Touch 3.1 doesn't work on the CR-X

Expected behaviour:
Z-Axis stops when hitting BL-Touch.

Actually:
Keeps running down until crash into bed.

I searched for Z- on the daughterboard to place the jumper, didn't see such a connector.

**Comment by InsanityAutomation** [comment]
BLTouch needs to go all the way back to the main board. If it doesnt stop, reverse the orientation of the black/white wire. They are polar and cant go both directions. Im running a 3.1 on mine here at the moment so it will work when wired correctly.
