### ISSUE TITLE
bug: CRX_BLTouch_DualFil_UBL_DW3 - G26 crashes printer

### ISSUE THREAD

**Issue by LMS0815** [InsanityAutomation/Marlin#61]
If you try to generate an UBL test print via OctoPrint terminal,  the printer is reset / hangs after few seconds.

```
G29 L
G29 J
G28
G26 B60 H200 F1.75 L0.2 S0.4 R16

```

same code had no issues with _CRX_BLTouch_DualRunout_2.0_B1.hex_

**Comment by InsanityAutomation** [comment]
Found a look with the print job timer stop, most likely impacts this too. Fix will be up shortly.

**Comment by InsanityAutomation** [comment]
Update is posted, thanks!

**Comment by LMS0815** [comment]
The issue is not solved. 
After homing
`G26 B60 H200 F1.75 L0.2 S0.4 R25`
crashes the head into the bed.
![IMG_20190909_101959](https://user-images.githubusercontent.com/8235214/64515265-8c54e700-d2ec-11e9-9669-c5eec8f15a67.jpg)

edit:
Seems the Head is moving beyond y-Axis to the right.

**Comment by InsanityAutomation** [comment]
Ill take a closer look at this one shortly

**Comment by InsanityAutomation** [comment]
Roxy fixed this one upstream
