### ISSUE TITLE
cosmetics: CRX_BLTouch_DualFil_UBL_DW3 - UBL LCD layout

### ISSUE THREAD

**Issue by LMS0815** [InsanityAutomation/Marlin#62]
1. The layout of the ABL/UBL menu needs to be revised.

The last two columns are _melting_.
![IMG_20190911_090235925](https://user-images.githubusercontent.com/8235214/64762158-e993a700-d53d-11e9-937f-8e01c08e61e2.jpg)

If possible:
- adjust spacing between columns.
- Add a '+' (or space) to positive values for alignment with the negative values.

2.  The printer message e.g. _TM3D CR-X Ready._ should be aligned with the label e.g. _Leveling Mode_

**Comment by InsanityAutomation** [comment]
Ill probably go after the cosmetic stuff after PLR is done. Ill keep this open and feel free to add more if you find it!

**Comment by LMS0815** [comment]
Obsolete due to new _CR-XABL_Screens_V2Rev1.1.7z_ with new issues.
