### ISSUE TITLE
Filament sensor does not work

### ISSUE THREAD

**Issue by SkullKill** [InsanityAutomation/Marlin#63]
### Description

branch CrealityDwin_2.0
running on CR-10S Pro

looks like the firmware is not considering the state of the Filament sensor 

### Steps to Reproduce

1. remove filament, sensor light turns off
2. heat up the hotend  > 195 degrees
3. press the FEED filament . it is trying to extrude instead of giving the no filament / change filament message.

OR

1. start a print
2. when the filament runs out, sensor light turns off, it continues printing

OR

1. start a print without any filament
2. printer still tries to print without any filament

**Expected behavior:** [What you expect to happen]
pause print, and ask to change/load filament

**Actual behavior:** [What actually happens]
continues the print as if the filament sensor has not been triggered.

#### Additional Information

Send: M412
Recv: echo:Filament runout ON
Recv: Filament runout distance (mm): 5.00
Recv: ok P15 B3

**Comment by LMS0815** [comment]
I have the same behavior with CR-X (and assumed my cabeling might be wrong. 

See: https://github.com/InsanityAutomation/Marlin/issues/53

**Comment by hdtechk** [comment]
I had a filament run out last night. I did get the screen pop up.   But extruder had done a retraction some time after sensor trigger and jammed filament back in to sensor when I hit yes to change filament it immediately started trying to print again

**Comment by SkullKill** [comment]
> I did get the screen pop up.

@hdtechk which branch are you using? is it the CrealityDwin_2.0 branch ?

https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin_2.0

**Comment by hdtechk** [comment]
Yes I'm using CrealityDwin_2.0

**Comment by SkullKill** [comment]
Apologies, this WAS a cabling issue!!!!, i just assume that the cabling was correct, because the led light was behaving as expected. replaced the cable, and it is working as expected!! 
at least output of M119 is....

2 out of 3 wires were working... it just so happen that the sensor wire was the bad one....

**Comment by LMS0815** [comment]
> Apologies, this WAS a cabling issue!!!!, i just assume that the cabling was correct, because the led light was behaving as expected. replaced the cable, and it is working as expected!!
> at least output of M119 is....
> 
> 2 out of 3 wires were working... it just so happen that the sensor wire was the bad one....

Kindly share the right wiring.

**Comment by SkullKill** [comment]
@LMS0815 this is on a CR-10S Pro, that already has the filament sensor. it is all already wired from factory, there is a break out board on the gantry to the sensor where it is originally.

for mine, since i converted my setup to a direct drive, i also moved the filament sensor to be on top of the excruder, which is on top of the hotend.... to do that, i had to make a new longer cable, it is a three cable harness, which i just copied from the original cable. basically, pin 1 to pin 1, pin 2 to pin 2, pin 3 to pin 3.

on mine, it was the green wire that was faulty, so the 1st pin, (sensor wire). the other 2 would be +ve and GND (since the light was working on mine), not sure in what order, but i can find out if you want?

https://www.thingiverse.com/thing:3807893

![CR-10S_Pro_Direct_Drive_Bracket_With_Sensor_Mount_V1 0_07_MountedRight](https://user-images.githubusercontent.com/20982257/64962741-8baee880-d8ca-11e9-812c-30944d81c5c2.jpg)
![CR-10S_Pro_Direct_Drive_Bracket_With_Sensor_Mount_V1 0_08_MountedFront](https://user-images.githubusercontent.com/20982257/64962743-8c477f00-d8ca-11e9-97b1-3ca50684cb60.jpg)
![CR-10S_Pro_Direct_Drive_Bracket_With_Sensor_Mount_V1 0_11_MountedBack](https://user-images.githubusercontent.com/20982257/64962744-8c477f00-d8ca-11e9-8ebd-28e1be01a295.jpg)



on the breakout board, i am quite sure that it is going to the X+ port. bottom left in the picture.

![CREALITY-3D-Ribbon-Cable-Breakout-Adapter-For-CR-10S-Pro-And-CR-X-3D-Printer2](https://user-images.githubusercontent.com/20982257/64964048-db8eaf00-d8cc-11e9-9f1a-0676307a3577.jpg)

@hdtechk 
not sure if that is helpful, but the M600 settings (which is used in a filament runout, i think) are in Configuration_adv.h
just under ADVANCED_PAUSE_FEATURE

i changed those settings to suite the direct drive setup on mine.
