### ISSUE TITLE
Fast Manual Feed Rate when Z-axis in motion

### ISSUE THREAD

**Issue by SkullKill** [InsanityAutomation/Marlin#64]
### Description

branch CrealityDwin_2.0
running on CR-10S Pro

Very Fast Manual Feed Rate (Pressing the FEED button on the LCD) when Z-axis in motion

### Steps to Reproduce

1. heat up hotend to >195 degrees
2. move z axis up, maybe 30mm (does not matter)
3. while z axis is still moving, press the "FEED" button on the LCD

**Expected behavior:** [What you expect to happen]

Feed at a slow rate

**Actual behavior:** [What actually happens]

it is feeding the filament at an extremely fast rate.

#### Additional Information

when the z axis has finish moving, the FEED button works as expected, feeding slowly.

**Comment by InsanityAutomation** [comment]
Sounds like an upstream ExtUI issue, but ill verify and see where it comes from.

**Comment by InsanityAutomation** [comment]
Ive confirmed this is resolved upstream between either Marcio's or my changes. Dont know which one for sure, but doesnt matter :)
