### ISSUE TITLE
Segmentation fault while compiling

### ISSUE THREAD

**Issue by ylpoonlg** [InsanityAutomation/Marlin#68]
### Description
When I tried to compile the code, there was an error message saying that in Marlin_main.cpp, there was a segmentation fault. I tried to look for the source of error, and ended up that if I comment out z_values[x][y] = NAN; on line2901, I can compile it successfully. I wonder if this was a bug or did I do anything wrong? Thanks for helping out!

### Steps to Reproduce
1. download the zip file containing the marlin code
2. open it in the Arduino IDE
3. compile the code

**Expected behavior:**
compile smoothly without error message

**Actual behavior:**
An error message appears when I try to compile the code

**Error message:**
sketch\Creality_DWIN.cpp: In member function 'void RTSSHOW::RTS_SndData(int, long unsigned int, unsigned char)':

sketch\Creality_DWIN.cpp:557:26: warning: right shift count >= width of type [-Wshift-count-overflow]

    snddat.data[0] = n >> 16;

                          ^

sketch\Marlin_main.cpp: In function 'reset_bed_level':

sketch\Marlin_main.cpp:2905:3: internal compiler error: Segmentation fault

   }

   ^

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/program files/windowsapps/arduinollc.arduinoide_1.8.21.0_x86__mdqgnx93n4wtt/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

**Comment by InsanityAutomation** [comment]
This is a gcc fault, and is usually transient in nature. Restarting the IDE and retrying usually recovers. The windows store version of the IDE is far more likely to exhibit issues like this.
