### ISSUE TITLE
Feature Request: Print X,Y,Z on kill screen

### ISSUE THREAD

**Issue by martaaay** [InsanityAutomation/Marlin#69]
### Description

On a fatal error (such as min temp), the printer shuts down as expected and displays a kill screen with the error. Getting back to restarting the printer where it left off is pretty difficult to get right, often leaving a seam or missing row. If I knew the last X,Y,Z or (better yet) the line of gcode from the kill screen, recovery would be a breeze.

**Comment by InsanityAutomation** [comment]
This would need to be done upstream and added to the kill messages. When SD printing lines are stored as file pointers, so that output wouldnt be as easy to use though.

**Comment by InsanityAutomation** [comment]
The development branch has this now, its being fed in the idle loop and last sent values are displayed.
