### ISSUE TITLE
T-Rex 2+ Chassis LED commands M225 and M224 no response

### ISSUE THREAD

**Issue by jim-edwards** [InsanityAutomation/Marlin#7]
### Description

The stock firmware for the T-Rex 2+ responded G-Code commands M225 and M224 to turn the chassis LEDs ON and OFF.  This built firmware no longer seems to respond to those commands.

### Steps to Reproduce

1. Send command M224 to turn LEDs off
2. Observe LEDs stay ON
3. Manually turn LEDs OFF in menu
4. Send command M225 to turn LEDs on
5. Observe LEDs stay OFF

Using stock T_Rex branch configuration with the following settings:

#define BedAC
#define tallVersion

**Comment by jim-edwards** [comment]
Looks like custom code was added to the source tree from Formbot:

ultralcd.cpp
```
	//
	//led on and off
	//
	#ifdef LED
	MENU_ITEM(gcode, MSG_LED_ON, PSTR("M225"));	
	MENU_ITEM(gcode, MSG_LED_OFF, PSTR("M224"));
        #endif
	#ifdef LASER
	MENU_ITEM(gcode, MSG_LASER_ON, PSTR("M3"));	
	MENU_ITEM(gcode, MSG_LASER_OFF, PSTR("M5"));
	#endif
	//MKS
```

language_en.h
```
//MKS

#ifdef LED
  #ifndef MSG_LED_ON
    #define MSG_LED_ON                        _UxGT("Led on")
  #endif

  #ifndef MSG_LED_OFF
  #define MSG_LED_OFF                         _UxGT("Led off")
  #endif
#endif
#ifdef LASER
#ifndef MSG_LASER_ON
    #define MSG_LASER_ON                        _UxGT("Laser on")
  #endif

  #ifndef MSG_LASER_OFF
  #define MSG_LASER_OFF                         _UxGT("Laser off")
  #endif
#endif

//MKS
```

**Comment by jim-edwards** [comment]
I have diffed the remaining stock code from the base 1.1.0 branch, outside of the Configuration and pin files, those seemed to be the only real changes.  Just to document my findings I will create a forked repo of the base system with the Formbot code as a separate commit so the diffs can be easily reviewed by all.

If you want those changes, let me know, I would be happy to create a PULL

Looks like the new firmware responds to the standard firmware M355 S0 or S1 instead of their custom commands.  Not sure if you want to support their customer commands or just document the differences.

**Comment by InsanityAutomation** [comment]
M224\M225 is documented as reserved for an as yet unsupported function - M224: Enable extruder during fast moves. / M225: Disable extruder during fast moves. Given this, I dont want to keep the custom command just to be burned later when it collides. The move to marlin standards was intentional.

Ill add a note in the configuration section though so it doesnt surprise anybody else. Youre the first ive heard try to use their custom command, since its not really documented anywhere!

**Comment by jim-edwards** [comment]
I agree, they were odd choices to begin with, I will update my documentation to show that as well
