### ISSUE TITLE
Software interrupt conflict when enabling bltouch as suggested by Antclads

### ISSUE THREAD

**Issue by mark2382** [InsanityAutomation/Marlin#78]
### Description
Compilation failure when trying to enable bltouch

### Steps to Reproduce
1.  "define ENDSTOP_INTERRUPTS_FEATURE" in configuration.h as suggested by Antclads manual for v3.1,
2. compile with visual studio code

**Expected behavior:** [What you expect to happen]
Successful compile

**Actual behavior:** [What actually happens]
Compilation error:
In file included from Marlin/src/HAL/HAL_STM32/../../inc/MarlinConfig.h:38:0,
                 from Marlin/src/HAL/HAL_STM32/HAL_SPI.cpp:25:
Marlin/src/HAL/HAL_STM32/../../inc/SanityCheck.h:2047:4: error: #error "Select hardware UART for TMC2208 to use both TMC2208 and ENDSTOP_INTERRUPTS_FEATURE."
   #error "Select hardware UART for TMC2208 to use both TMC2208 and ENDSTOP_INTERRUPTS_FEATURE."

#### Additional Information
That looks like in pins_BIGTREE_SKR_PRO_V1.1.h  I need to uncomment lines 125-135 and comment lines 140-156. Alternately, there is a define "TMC_USE_SW_SPI" that could be used to select between the two (see line 106). 

I have not tried this workaround yet as I have decided to get things working with builtin sensor.

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by InsanityAutomation** [comment]
ENDSTOP_INTERRUPTS_FEATURE has not proved to be valuable for the BLTouch in any cases seen, and in fact caused more issues on the STM32 platforms as discussed on the Marlin discord. I will reach out to Paris about revising the documentation.
