### ISSUE TITLE
CR-X UBL and MeshExtreme too large for memory

### ISSUE THREAD

**Issue by flommy** [InsanityAutomation/Marlin#81]
### Description

Compilation of CR-X (stock hotend and touch display) with BLTouch, UBL and MeshExtreme does not fit the microcontroller.

### Steps to Reproduce

Active defines in configuration.h:
#define MachineCRX
#define HotendStock
#define BedDC
#define ABL_BLTOUCH
#define Force10SProDisplay
#define ABL_UBL
#define MeshExtreme

Compiled with Arduino 1.8.9 on Win7.

**Expected behavior:**

Code compiles without errors.

**Actual behavior:**

> Sketch uses 190910 bytes (75%) of program storage space. Maximum is 253952 bytes.

>Global variables use 8304 bytes (101%) of dynamic memory, leaving -112 bytes for local variables. >Maximum is 8192 bytes.
>Not enough memory; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing your footprint.
>Error compiling for board Arduino/Genuino Mega or Mega 2560.

**Comment by InsanityAutomation** [comment]
Unfortunately there isnt much I can do about the memory usage there. Extreme is overkill for a 300mm bed, I only use it with 500mm machines myself. Some recent changes have been reducing dynamic memory in exchange for program memory so there is a chance the next update will be better, but thats not a suggested configuration.
