### ISSUE TITLE
CR-X config examples

### ISSUE THREAD

**Issue by LMS0815** [InsanityAutomation/Marlin#82]
Please upload working example files for CR-X

https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin_2.0/config/examples/Creality

**Comment by InsanityAutomation** [comment]
The touchscreen machines will end up with broken out configurations when the ExtUI module is at a point to be merged upstream. That will be when PLR is fully implemented. If examples are put in before it will likely lead to a rash of issues where people are surprised when the touchscreen no longer functions.
