### ISSUE TITLE
M851 not parsed correctly (CR-X)

### ISSUE THREAD

**Issue by LMS0815** [InsanityAutomation/Marlin#83]
If you sent `M851 X-12.5  Y-38.0 Z-1.7` not all offset coordinates are set.
According to [M851 - XYZ Probe Offset](http://marlinfw.org/docs/gcode/M851.html) this should work.
If you issue the command separately 
```
M851 X-12.5
M851 Y-38.0
M851 Z-1.7
```

The values are set correctly (You can probe it with `M851`)

**Comment by InsanityAutomation** [comment]
There were upstream casting issues with float values set by M851. The devel branch has these fixes merged in.
