### ISSUE TITLE
Compile errors with TOUCH_MI_PROBE enabled

### ISSUE THREAD

**Issue by juanpa669** [InsanityAutomation/Marlin#84]
### Description

Some compile errors occured with TOUCH_MI_PROBE enabled
I tried to fix errors by updating some code with that done it compile, but touch mi sensor does not work

### Steps to Reproduce

1. #define TOUCH_MI_PROBE

**Expected behavior:** Compile without errors

**Actual behavior:** Throw compile errors

#### Additional Information

What I update according errors:

Add TOUCH_MI_PROBE because of Error Only one sensor must be enabled
```
#if(ENABLED(MachineCR10SPro))
  #define MachineCR10Std
  #if DISABLED(ABL_BLTOUCH, ABL_EZABL, TOUCH_MI_PROBE)  
    #define ABL_NCSW
  #endif
  #if DISABLED(ABL_UBL)
    #define ABL_BI
  #endif
  #define MeshStd
  #define lerdgeFilSensor
#endif
```
Same here
```
#if DISABLED(ABL_EZABL, ABL_NCSW, ABL_BLTOUCH, TOUCH_MI_PROBE)
  #define PROBE_MANUALLY
  #define MANUAL_PROBE_START_Z 0.2
#endif
```

```
// @section machine
// The size of the print bed
#if NONE(ABL_EZABL, ABL_BLTOUCH, ABL_NCSW, TOUCH_MI_PROBE)
```

```
//#define AUTO_BED_LEVELING_3POINT
//#define AUTO_BED_LEVELING_LINEAR
#if (ENABLED(ABL_EZABL)|| ENABLED(ABL_BLTOUCH) || ENABLED(ABL_NCSW)|| ENABLED(TOUCH_MI_PROBE))
  #if ((ENABLED(ABL_UBL)))
    #define AUTO_BED_LEVELING_UBL
    #endif
    #if ((ENABLED(ABL_BI)))
      #define AUTO_BED_LEVELING_BILINEAR
    #endif
#elif (DISABLED(OrigLA))
  #define MESH_BED_LEVELING
#endif
```
```
/**
 * Add a bed leveling sub-menu for ABL or MBL.
 * Include a guided procedure if manual probing is enabled.
 */
#if NONE(ABL_EZABL, ABL_NCSW, ABL_BLTOUCH, TOUCH_MI_PROBE) && (DISABLED(MachineCRX) || ENABLED(GraphicLCD))
#define LCD_BED_LEVELING
#endif
```

Fix for compile Error Babystep
configuration_adv.h
```
  #if ANY(ABL_EZABL, ABL_BLTOUCH, ABL_NCSW, TOUCH_MI_PROBE)
    #define BABYSTEP_ZPROBE_OFFSET          // Combine M851 Z and Babystepping
  #endif
```

```
/**
 * Repeatedly attempt G29 leveling until it succeeds.
 * Stop after G29_MAX_RETRIES attempts.
 */
#if ENABLED(ABL_BI) && NONE(MachineCR10Orig, LowMemoryBoard, TOUCH_MI_PROBE)
  #define G29_RETRY_AND_RECOVER
#endif
```

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
[Configuration.zip](https://github.com/InsanityAutomation/Marlin/files/3937040/Configuration.zip)

**Comment by InsanityAutomation** [comment]
For the TouchMi, you would probably want to enable ABL_BLTOUCH then comment out the actual bltouch line below and enable the touchmi. That tells everything it has a probe as expected. That is not a piece of hardware I have here, so I cant support it.
