### ISSUE TITLE
CR-X: CRX_BLTouch_DualFil_UBL_DW5  G29 J creates Firmware ERROR

### ISSUE THREAD

**Issue by LMS0815** [InsanityAutomation/Marlin#86]
Sending `C29 J; Grid leveling` crashes the Firmware and Octoprint is loosing connection.

**Comment by patadeloso** [comment]
Seems to happen with CRX_BLTouch_NoFil_UBL_DW5.hex too

Send: G28
[...]
Recv: echo:busy: processing
Printer seems to support the busy protocol, will adjust timeouts and set busy interval accordingly
[...]
Recv: echo:busy: processing
[...]
Recv: echo:busy: processing
[...]
Recv: echo:busy: processing
[...]
Recv: echo:busy: processing
[...]
Recv: Error:Printer halted. kill() called!
Changing monitoring state from "Operational" to "Error: Printer halted. kill() called!"
Send: M112
Send: N2 M112*35
Send: N3 M104 T0 S0*34
Send: N4 M104 T1 S0*36
Send: N5 M140 S0*96
Changing monitoring state from "Error: Printer halted. kill() called!" to "Offline (Error: Printer halted. kill() called!)"
Connection closed, closing down monitor

**Comment by LMS0815** [comment]
Solved in DW6 (CRX_BLT_UBL_Fil_DW6.hex)

**Comment by LMS0815** [comment]
solved: DW6
