### ISSUE TITLE
CR-10S PRO DW5 print screen display

### ISSUE THREAD

**Issue by hdtechk** [InsanityAutomation/Marlin#87]
X and Z locations displayed on print screen are reversed.   X displayed is actually Z. 
And Z displayed is actually X
![IMG_20191221_005835215](https://user-images.githubusercontent.com/19457559/71305270-72687d00-238e-11ea-8c05-58872586d86d.jpg)

**Comment by InsanityAutomation** [comment]
That file was up for about 2 hours before it was fixed. If you pull the current files it should be resolved! Sorry for the last second typo!
