### ISSUE TITLE
Bed Size of CR-10 Max wrong

### ISSUE THREAD

**Issue by Pixelshading** [InsanityAutomation/Marlin#88]
In the Configuration.h the Printbed Size for the CR-10 Max is set to: 

X=475 Y=450 Z=470

but the actual working Printbed Size is:
X=450 Y=450 Z=470.

**Comment by InsanityAutomation** [comment]
Ill take a look at it again. I dont have a machine physically here but the positioning was set to allow the head to move the full distance and probe more of the bed than it could if the nozzle was limited to only the bed position.

**Comment by InsanityAutomation** [comment]
This was resolved along the list of M851 changes
