### ISSUE TITLE
Out of filament message after every print

### ISSUE THREAD

**Issue by marcinbauer-ohf** [InsanityAutomation/Marlin#90]
### Description
I get an: "No filament click yes to change filament or no to Cancel"

### Steps to Reproduce
1. Print whatever.

#### Additional Information
My configs:
[config.zip](https://github.com/InsanityAutomation/Marlin/files/4008459/config.zip)

Photo:
![IMG_20191229_193410](https://user-images.githubusercontent.com/6719575/71561527-f3eb9980-2a77-11ea-8cd4-fa7ac210d171.jpg)

**Comment by InsanityAutomation** [comment]
Are you able to get a serial log of when this occurs? Can you attach a gcode file of anything it occurs with? I wasnt able to reproduce here.

**Comment by Guilouz** [comment]
For me, I have this message with a PID command via Pronterface when it's done.

**Comment by juanpa669** [comment]
AS @Guilouz  I got runout filament dialog box after PID with the button Tools->Hotend PID auto tune.
Did you know if your new PID values are stored in EEPROM @Guilouz ?

**Comment by Hyrules** [comment]
I have the same message in pronterface with PID and with touchscreen in menu PID autotune.

This is still present as DW6

**Comment by InsanityAutomation** [comment]
Applied a fix in the Bleeding branch, can you give it a shot?

**Comment by Hyrules** [comment]
I will try this fix. Keep you posted in a day or two.

**Comment by Hyrules** [comment]
Ok got time to test and unfortunately this is not working. I still have a No filament error after sending a pid autotune.

SENDING:M303 S200 U1
PID Autotune start
 bias: 77 d: 77 min: 197.37 max: 207.86
 bias: 76 d: 76 min: 196.84 max: 203.57
 bias: 76 d: 76 min: 197.24 max: 203.57 Ku: 30.55 Tu: 28.50
 Classic PID
 Kp: 18.33 Ki: 1.29 Kd: 65.31
 bias: 75 d: 75 min: 197.11 max: 203.57 Ku: 29.54 Tu: 28.68
 Classic PID
 Kp: 17.72 Ki: 1.24 Kd: 63.53
 bias: 75 d: 75 min: 197.20 max: 203.57 Ku: 29.99 Tu: 28.83
 Classic PID
 Kp: 18.00 Ki: 1.25 Kd: 64.85
PID Autotune finished! Put the last Kp, Ki and Kd constants from below into Configuration.h
#define DEFAULT_Kp 18.00
#define DEFAULT_Ki 1.25
#define DEFAULT_Kd 64.85
ok P7 B3
==onUserConfirmRequired==
//action:prompt_end
//action:prompt_begin M1 Stop
//action:prompt_button Continue
//action:prompt_show
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user

**Comment by Hyrules** [comment]
We'll it does not work when sending a command through pronterface but it does not seem to happen when I use the menu on the printer.

**Comment by InsanityAutomation** [comment]
If the issue only persists from pronterface id have to see the ful log of whats sent. I cant see anything left machine side that would cause it.

**Comment by InsanityAutomation** [comment]
Im closing this as I havnt heard any update. If it comes up again, just reopen the issue.
