### ISSUE TITLE
Different current values for E0 and E1 by default?

### ISSUE THREAD

**Issue by CarlitoGrey** [InsanityAutomation/Marlin#94]
Hey,

I'm just stepping through Marlin to build for an SKR 1.1 Pro on a CR-X. I just noticed that in configuration_adv.h the current values for E0 and E1 differ, it looks like they should be set the same so thought I'd raise it here?

  #if AXIS_IS_TMC(E1)
    #define E1_CURRENT      800
    #define E1_MICROSTEPS    16
    #define E1_RSENSE         0.11
    #define E1_CHAIN_POS     -1
  #endif

  #if AXIS_IS_TMC(E2)
    #define E2_CURRENT      800
    #define E2_MICROSTEPS    16
    #define E2_RSENSE         0.11
    #define E2_CHAIN_POS     -1
  #endif

**Comment by InsanityAutomation** [comment]
Looks like E0 and E1 match now, not sure when the overlap was when it got fixed but ill go ahead and close this.
