### ISSUE TITLE
CR10SPro new PID not stored in EEPROM

### ISSUE THREAD

**Issue by juanpa669** [InsanityAutomation/Marlin#98]
### Description

Use of PID auto tune buttons do not save new PID values in EEPROM.
Plus in my case at the end of auto tune it open the runout filament dialog box and wait until click on YES or NO. If click YES return to screen like a print is running, have to click STOP print to take by the hand on the printer.

### Steps to Reproduce

1. Run a PID auto tune 
2. Power off  the printer
3. On power on M503 gives the configuration.h values

**Expected behavior:** Values was stored in EEPROM

**Actual behavior:** Gives the default values written in Configuration.h

#### Additional Information
Runout filamament dialog box at the end of process

```
    #define USER_DESC_2 "PID Tune"
    #define USER_GCODE_2 "M106S128\nM303C8S215E0U\nM500\nM117 PID Tune Done"
```
[Configuration.zip](https://github.com/InsanityAutomation/Marlin/files/4142763/Configuration.zip)

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

**Comment by InsanityAutomation** [comment]
The store settings button should be used when you are satisfied with the new PID. Autotune is not always perfect and it should be validated. You do not want it overwriting the original values on you right away if its not validated.
